### ISSUE TITLE
Different options for GCM and APN

### ISSUE THREAD

**Issue by rodrigok** [raix/push#100]
For Android we can use title, but for iOS we need to embed title in message, so if exists an option to override this attributes based on service would be more easy to have great notifications in different environments.

Could be:

```js
    Push.send({
        from: 'push',
        title: 'Hello',
        text: 'world',
        badge: 1, //optional, use it to set badge count of the receiver when the app is in background.
        apn: {
            text: 'Hello: world'
        },
        query: {
            // Ex. send to a specific user if using accounts:
            userId: 'xxxxxxxxx'
        } // Query the appCollection
        // token: appId or token eg. "{ apn: token }"
        // tokens: array of appId's or tokens
        // payload: user data
        // delayUntil: Date
    });
```

**Comment by rubenlpz** [comment]
Requirement solved by RAIX, check in advanced in documentation: 

> #### Overwriting platform specific values
> If needed it's possible to specify values pr. platform `apn`/`gcm` in the send.
> Eg.:
> ```js
> Push.send({
>   from: 'Test',
>   title: 'Hello',
>   text: 'World',
>   apn: {
>     // apn specific overwrites
>     title: 'sent via apn'
>   },
>   gcm: {
>     // gcm specific overwrites
>     title: 'sent via gcm'
>   },
>   query: {}
>   token: {}
>   tokens: [{},{}]
>   delayUntil: new Date()
> });
> ```
> *You can overwrite keys: 'from','title','text','badge','sound' and 'notId'*
