### ISSUE TITLE
Clear background notifications when user opens the app

### ISSUE THREAD

**Issue by VioletaCalvo** [raix/push#102]
Hi!

First of all, thank you for your package! :blush: 

Is there a way to clear phone notifications received on the background when user opens the app? I cannot find this in the documentation.
I'm using multiple notifications on android.
Thank you in advance!

**Comment by center777** [comment]
+1

**Comment by raix** [comment]
it's in the event Push.on("message") - push notifications will not show when the app is open - the app should decide how to display eg. by using the local notifications or other custom way

**Comment by linyuanbin** [comment]
directly发自我的手机-------- 原始邮件 --------发件人： Violeta ***@***.***>日期： 2022年4月20日周三 00:49收件人： raix/push ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [raix/push] Clear background notifications when user opens the app (#102)
Closed #102.
