### ISSUE TITLE
open different views via push notification

### ISSUE THREAD

**Issue by rlech** [raix/push#107]
someone can give me a hint how to open different views from the app via push notifications?

e.g. if someone comment a thread and I got a push notification it will send me to the push related thread.

**Comment by VioletaCalvo** [comment]
+1

**Comment by urossmolnik** [comment]
You have to manually handle push notification. You can send some payload data too, so you don't have to rely on message content. 

### Example

#### Sending notification:
```js
Push.send({
    from: 'main',
    title: title,
    text: text,
    query: {userId: userId},
    payload: { gotoView: 'thread', threadId: threadId }
  });
```

#### Handling notification:
```js
var handlePushPayload = function(payload) {
  if (!payload) return;
  if (payload.gotoView === 'thread') {
    // Do something within your framework
  }
};

// Called when message recieved on startup (cold+warm)
Push.addListener('startup', function(notification) {
  handlePushPayload(notification.payload);
});
```

**Comment by rlech** [comment]
perfect. thx.

**Comment by VioletaCalvo** [comment]
Thank you !

**Comment by VioletaCalvo** [comment]
I'm using multiple notifications and when I use the ```'startup'``` listener I get allways last notification received, not selected one. I mean the ```Push.addListener 'startup'``` code executes last notification. Is this a bug or Is there another way to proceed?
Thank you!
```coffeescript
Push.addListener 'startup', (pushNotification) ->
   # Here pushNotification is allways last notification received, no the selected one to open the app

**Comment by xpluscal** [comment]
+1

**Comment by raix** [comment]
Theres a `startup` event triggered when user opens the app via a notification - eg. tapping.
If the user is already in the app - the app is in "foreground" - theres a `message` event triggered instead.

**Comment by java99** [comment]
Is Push.addlistener on Client sufficient?

Mine is not working  should I add Push.on(message)?
