### ISSUE TITLE
How can I play a specific sound? 

### ISSUE THREAD

**Issue by Tzikas** [raix/push#111]
Is there a way to play a specific sound.  I saw this topic in a previously closed issue, but it didn't seem resolved.  I have a default sound playing, but I want to pick a sound.  In my config.push.json:
{
  "apn": {
    "passphrase": "********!",
    "key": "********",
    "cert": "********"
  },
  "apn-dev": {
    "passphrase": "********",
    "key": "********",
    "cert": "********"
  },
  "production": false,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true

On my server file: 

Push.send({
					from: 'push',
					title: 'Hello World',
					text: 'This notification has been sent from the SERVER',
					badge: badge,
					payload: {
						title: 'Hello World',
						historyId: result
					},
					query: {},
					sound: '../public/sound.mp3'
				});

**Comment by Tzikas** [comment]
Use `www/application/public/sound.mp3` from https://github.com/raix/push/issues/36, and MAKE SURE IT"S NOT TOO LONG OF A SOUND or it will default, and ruin many hours of your life.

**Comment by guilhermedecampo** [comment]
Thanks for that! =)

**Comment by kylepierce** [comment]
What sound length is too long. 1 second? 2? 5?

**Comment by Tzikas** [comment]
I think its about 40 seconds, but you can find out in apple's push notification docs

**Comment by kylepierce** [comment]
I would immediately delete any app had a push notification sound longer than 10 seconds. Thats crazy lol

**Comment by mvgalle** [comment]
Please see my comment here: https://github.com/raix/push/issues/9#issuecomment-159422348
