### ISSUE TITLE
Push Notification Does Not Alert When Meteor App Is Active

### ISSUE THREAD

**Issue by panthongw** [raix/push#12]
Hi Morten,

I finally got the bar notification working for Android. However, I notice that when I am on the Meteor app the notification does not trigger until I am on a different app or the phone is locked.

Is this an intended behavior?

**Comment by ndevr** [comment]
BTW: Notifications (alerts) for iOS also not work.

**Comment by dennisharrison** [comment]
@ndevr Do you mean when the app is open?  They aren't supposed to.  

Are the listeners not working?  I haven't tested them yet - will be there later this week though.

**Comment by ndevr** [comment]
@dennisharrison Yes, when die app is open.

There are no listeners registered when i'am debugging it.

**Comment by panthongw** [comment]
According to this thread @raix mentions that this is expected behavior
https://github.com/raix/push/issues/13

**Comment by omsharma007** [comment]
use this 
```
Push.addListener('alert', function(notification) `{`
     alert( 'App is running in foreground' );
    });
```
