### ISSUE TITLE
Push.Error: Error: No value for android

### ISSUE THREAD

**Issue by nickw** [raix/push#124]
I'm running `raix:push@3.0.0` and my client config looks like this:

```
Meteor.startup(function() {
  Push.debug = Meteor.settings.public.push.debug;
  Push.Configure({
    gcm: {
      projectNumber: Meteor.settings.public.push.gcm.projectNumber
    },
    alert: false,
    sound: true,
    vibrate: true
  });
});
```

My `settings.json` looks like:

```
{
  "public": {
    "push": {
      "debug": true,
      "gcm": {
        "projectNumber": "XXXX"
      }
    }
  }
}
```

I'm getting the following error:

<img width="614" alt="screen shot 2015-10-01 at 5 39 41 pm" src="https://cloud.githubusercontent.com/assets/3907/10237449/66f9c90c-6866-11e5-9e46-71d68370354b.png">

I'm assuming this means my `gcm` config isn't getting correctly translated to an `android` key for `phonegap/phonegap-plugin-push`?

**Comment by raix** [comment]
This is the reason for the major version bump :)

https://github.com/raix/push/blob/v3.x/docs/ADVANCED.md (the outdated part)

https://github.com/phonegap/phonegap-plugin-push#pushnotificationinitoptions

**Comment by nickw** [comment]
_What_ is the reason for the major version bump?

_Which_ part of that doc is outdated? Everything past the "OUTDATED" header?

The code _seems_ to still be using the `gcm` config: https://github.com/raix/push/blob/v3.x/lib/client/browser.js#L215

Are you saying that in `3.0.0` we should use `PushNotification.init(options)` directly rather than using `Push.Configure`?

**Comment by nickw** [comment]
Ok, after digging into more I think I've determined that this is the correct config:

```
Push.Configure({
    android: {
      senderID: Meteor.settings.public.push.gcm.projectNumber
    },
    sound: true,
    vibrate: true
  });
```

I'll submit a PR to update the docs as that is very unclear currently.
