### ISSUE TITLE
Only Bar Notification Available - Android

### ISSUE THREAD

**Issue by panw** [raix/push#13]
Sorry for all the posts Morten.

I am trying to enable alerts and badges, so I added the following init code to the client. However, I only get the top bar alert. This might be due to this issue I reported [here](https://github.com/raix/push/issues/12).

`Push.init({ gcm: { "projectNumber": 917501955460 }, alert: true, bagde: true });`

Thanks for your help and the package. Happy Holidays.

**Comment by adamgins** [comment]
@panthongw @raix just wondering if you got this working. I just enabled GCM, was pretty easy compared with APN (took a few mins, compared with days of APN certificate hell).

When I am not in the app and a GCM notification is received, I hear a whistle but don't get any visual 

```
I20150109-15:19:06.137(11)? send to token { gcm: 'somelongtoken' }
I20150109-15:19:06.138(11)? sendGCM [ 'somelongtoken' ] { from: 'aginsburg',
I20150109-15:19:06.138(11)?   title: 'Some title',
I20150109-15:19:06.138(11)?   text: 'aginsburg commented on Conversation 149',
I20150109-15:19:06.138(11)?   createdAt: Fri Jan 09 2015 15:18:56 GMT+1100 (AEDT),
I20150109-15:19:06.138(11)?   createdBy: '<SERVER>',
I20150109-15:19:06.139(11)?   badge: 1,
I20150109-15:19:06.139(11)?   query: { userId: '5fa195c4721877522f5893e2' },
I20150109-15:19:06.139(11)?   _id: 'woBT5QiNmBZX5aKqX' }
I20150109-15:19:06.145(11)? Create GCM Sender using "Asomelongtoken"
I20150109-15:19:06.146(11)? A:Send message to: somelongtoken
I20150109-15:19:06.147(11)? Push: Sent message "Some title" to 1 ios apps 1 android apps
I20150109-15:19:07.437(11)? ANDROID: Result of sender: {"multicast_id":8192813545181402000,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1420777267260348%4664a0c26e2d5fd0"}]}

```

Note if I am in the App, I DO see an alert... it's just that I don't see an alert badge when looking at the app icon on the desktop. Not I am new to Android, so it may be a setup issue.

**Comment by raix** [comment]
try enabling badge in the config.push.json

**Comment by adamgins** [comment]
Actually I got the config JSON things sorted out.. that was my issue.

I am getting notifications on android.. I see the "unread" (badge) in the notifications pull down but I don't see it on the app Icon like a do on iOS (perhaps this is how Android works). I am still egtting the error above... which seems related to me.. I have not looked into the raix:push code yet.

**Comment by adamgins** [comment]
Ah, I think I found my issue, I was calling Push.Configure in the client and it was throwing a should not be called more than once exception.

The reason I was doing this I thought I had to call it in the client once the user is logged in... ie it gets called when the app first fires up before the user logs in (but the userId will be null)... so once the user logged in I called it again. 

Is this wrong? Perhaps I should move this to another thread?

**Comment by raix** [comment]
Yep you should only use the config - the package should have a computation listening on userid changes and update the appCollection... If not its a bug

**Comment by panthongw** [comment]
I've tested it again and I am still not getting any bar notification when the app is open nor icon badgee when the app is closed. 

I do get noise without having to set that option.

Would this is be device specific? I am testing on an HTC One running 4.1.2. 

@adamgins did you have any luck getting it to work?

**Comment by raix** [comment]
There will be no bar notification when the app is open - thats expected behaviour.
You can use the startup or message events to trigger a behaviour.

The badge should update when the app is closed - not sure why its not working - did you set badge:true in the config file? (it have to be boolean true not string "true")

**Comment by panthongw** [comment]
@raix in my config.push.json file I do set the badge option to a boolean true
```
{
  "gcm": {
    "apiKey": "xxxxxxxxxxxxxxx",
    "projectNumber": xxxxxxxxxxxx
  },
  "production": true,
  "badge": true
}
```

This is how I am sending a push message from the console:
```
Push.send({
        from: 'push',
        title: 'Hello',
        text: 'world',
        query: {} 
    });
```

Please let me know if something is off.

**Comment by adamgins** [comment]
I think I have the same issue as well. I do see notifications on the pull down menu (ie if I drag my finger down from top of screen)  and the badgecount is correct... it just does not show on the App icon (like iOS)

**Comment by raix** [comment]
Does android support badge/msgCount? Im not sure

**Comment by raix** [comment]
On the app icon that is

**Comment by raix** [comment]
Is this still an issue on the latest?

**Comment by adamgins** [comment]
No an issue fro me anymore, not sure about @panw

**Comment by panw** [comment]
I currently do not have an Android phone to test, so we could go ahead and close the issue and if I run into this issue in the future I'll submit a new issue.

**Comment by raix** [comment]
Super :)

**Comment by adim86** [comment]
I am having this exact problem, did anyone find a solution to it yet?

**Comment by bhaumikdesai91** [comment]
Hi @raix awesome API, we appreciatee your work.
I am currently trying to integrate your api in a demo project, I've managed to get the notifications correctly, but the badges count does not update on iOS device, I have read this thread thoroughly but nothing seems to work for badges, Please help me on this.. thank in advance. :)

**Comment by mitiaptest** [comment]
@raix Can you help me to work vibration and sound with notification on iOS?

**Comment by sahanDissanayake** [comment]
Yes confirmed this is still happening !! There are no badge on the icon and also if you send multiple push notifications from the server then one notification on the phone is replaced by the next notification on ANDROID

**Comment by vinnie1234** [comment]
Same problem here @sahanDissanayake. Android 6 with an Galaxy s7 Edge!
