### ISSUE TITLE
Common settings (e.g. 'production') not read from config.push.json

### ISSUE THREAD

**Issue by tdenovan** [raix/push#137]
I think there's a typo in the clone function in push.configuration.js which is preventing common settings (e.g. production) from being read correctly. I've created a pull request to fix it.

**Comment by boxxa** [comment]
Is this resulting in the debug message:

**Comment by tdenovan** [comment]
Yep, the PR which fixes this has been merged.

**Comment by boxxa** [comment]
Yep! Would suggest this be closed. Cloned locally, updated version to 3.0.2 and updated. Fixed! Thank you!

**Comment by boxxa** [comment]
Can you up the package.js to 3.0.2 to it can sync with Atmosphere?

**Comment by raix** [comment]
It should be published?
