### ISSUE TITLE
Using two apps

### ISSUE THREAD

**Issue by Streemo** [raix/push#148]
App 2 only sends notifications to users of App 1, and vice versa. I was thinking of implementing this using raix:push, using the Push.config calls on the client and server. I would specify app 1 client to use the key which app 2 server is using, and vice versa. Is this supported?

**Comment by Streemo** [comment]
Actually, this isn't necessary in my case -- I just need App 1's server to send notifications to app 2, and vice versa. Is this possible with this package, or does this package not support it?

**Comment by Streemo** [comment]
OK, so I solved this by including one more node in the process:

Instead of having Server2 notify App1, and Server1 notify App2, we can have Server2 call Server1 to notify App1, and Server1 call Server2 to notify App2.

A lot easier to implement, but requires n=3 trips instead of n=2.

**Comment by Streemo** [comment]
see #150 in order to do this you have to have each app specify differently namespaced collections and methods. 

It doesn't seem like one can do this using the config. It would be nice if this could all be done in the config for multi-app situations. +1 for this feature.

In the meantime, there is a simple way around this:

1. `cd yourapp && mkdir packages`
2. `git clone https://github.com/raix/push.git`
3. `cd push`
4. open `package.js`
5. change the name to `yourname:push`, and the version to `'0.0.1'`.
6. go into all files under `lib` and replace all instances of `'raix'` with `'yourUniqueAppNamespaceString'`
7. go into your application root, and run `meteor add yourname:push`.

Do this for all apps which use `raix:push` and which also use the same database.

Now, you should be able to push to different apps, with all push data being stored orthogonally. Otherwise, both apps will attempt to push each other's notifications.

**Comment by raix** [comment]
You could also just point the push.appCollection and push.notificatiins to new mongo collections

**Comment by raix** [comment]
Btw. Its partially implemented app namespacing, default name is "main"

**Comment by Streemo** [comment]
I like your suggestion, a lot simpler than rewrapping the package itself.

There is a problem with method names being equal, though. For example if I call `Meteor2.call('raix:push-update')` and I have the same method `'raix:push-update'` in the current app, then won't that be run as well as a "stub"? If so, then those names would need to be different too. I saw the name="main" thing, but wasn't sure how to change it through the API.


Thanks.

**Comment by Streemo** [comment]
Well, I am going to close this. The solution was to use separate collections if the two different apps are connected to the same database. I think the collection names should be configurable!

```
//config.push.json
{
  ...
  appCollection:"my-app-collection",
  notificationCollection: "my-notifications",
  ...
}
```
