### ISSUE TITLE
Notification success inconsistent

### ISSUE THREAD

**Issue by Streemo** [raix/push#149]
Android. Is anyone else having a problem where the notification succeeds (does not throw), but only actually notifies the user part of the time? Am testing it with the app either closed or in the background. I'd say it works about half the time. Based on my server logs, Push.send is successfully called every single time, and has the correct token/userId associated with it. For some reason, a significant portion of the messages are not getting to the user.

I'm not really asking for a solution (I have not provided enough information), but I am wondering if anyone else has, at all, noticed something of a similar character. I'll do more debugging -- just curious if this is a common problem with this package. Has anyone else noticed success inconsistency, or do your notifications work close to 100% of the time? 

Again, not looking for a solution -- just a show of hands, really. If you noticed a similar problem and fixed it, feel free to share what was wrong and how you fixed it.

Thanks!

**Comment by raix** [comment]
Sounds odd - normally the notifications arrive just a sec after being sent - I haven't had a 50% drop of messages.

Notes:
1. Theres no guarantee that the notifications will be sent (on gcm/apn services)
2. Some networks can block notifications

**Comment by andykingking** [comment]
I've had hugely variable results with notifications. Sometimes they arrive quickly and reliably, however sometimes I get massive drop rates for a period. 

@raix 's notes above are accurate. APN/GCM push notifications are designed for non-business-critical notifications rather than for reliability and end-to-end performance.

It would be ideal (although a fair amount of work) if this package had pluggable service-providers for pushes so you could slot in different approaches depending on your use case.

**Comment by Streemo** [comment]
While we're talking about it, have you also noticed that there are various types of notifications? For example, on android, certain notifications light up the screen when it's off, and show up as a card on the lock screen. I've set all of the raix:push options to "true", but these notifications are still the "weaker" kind -- not sure why. 

Do you know of any push services which guarantee delivery to the user? For example, in an on-demand service, it is necessary to get information to the user that their "X" is ready or cancelled, etc. 

I'm wondering if there's a way in raix:push to retry notifications until they are successfully passed through APN/GCM.

**Comment by Streemo** [comment]
#150 I think is the source of my problem. I'm telling server1 to send notifications to app1, but server2 ends up trying to send it to app1, because both are connected to the same database.

**Comment by andykingking** [comment]
I've never delved very deep into notifications, so I don't know a lot about them, or their forms.

If you're keen on reliability, you can look into tech like XMPP or MQTT, which (at varying levels) can provide features like guaranteed delivery. You won't get everything wrapped up in a nice package like this one though, there will be some work to integrate these.

I hope you found your issue!

**Comment by Streemo** [comment]
I am going to close this. The issue was that I was using two different applications (both connected to the same DB) without using different collections for each app's push package. Since both apps were pulling from the same collections, there was a cross-contamination between both apps. Thanks for all responses :)

**Comment by mvgalle** [comment]
I have also had inconsistent successful notificstions.

**Comment by andykingking** [comment]
@mvgalle IMO most of the time the issue is in code, configuration, or (least likely) network/GCM issues rather than the package. Do you have more specific data on your issue?
