### ISSUE TITLE
Getting Exit code 1 on Push.send from browser console

### ISSUE THREAD

**Issue by adamgins** [raix/push#15]
Hi,

I am using Push 2.3.2 on local server.

I am trying to debug why my second app on a different device does not seem to be registering the token, so I was just using the browser console on my laptop to send a message, like so:
`Push.send({from:"adam", title:"test1", count:22,text:"hello1",query:{userId:"2b3b4baad159b8a6d0352ad9"}})`

This is what I see on the console:

```
I20141230-14:36:29.529(11)? info: Push: Send message "test1" via query userId=2b3b4baad159b8a6d0352ad9
I20141230-14:36:29.532(11)? info: send to token apn=7f4d6e8afd3e27aa3251481059d9fcee46cdb18fd0742ab7829304940128a217
I20141230-14:36:29.534(11)? info: Push: Sent message "test1" to 1 ios apps 0 android apps
=> Exited with code: 1
```

I checked `Push.appCollection.find().fetch()` and I see:

```
> Push.appCollection.find().fetch()
[ { _id: '8tiSHNaT2vN7T44Xt',
    appName: 'main',
    createdAt: Tue Dec 30 2014 13:52:19 GMT+1100 (AEDT),
    token: { apn: '7f4d6e8afd3e27aa3251481059d9fcee46cdb18fd0742ab7829304940128a217' },
    updatedAt: Tue Dec 30 2014 14:19:06 GMT+1100 (AEDT),
    userId: '2b3b4baad159b8a6d0352ad9' } ]

```

Any ideas?

**Comment by adamgins** [comment]
@raix happy new year.. yep. I have got my system working but not sure I fully understand the science vs the voodoo... ;-)  I will try and write up soon.

**Comment by panthongw** [comment]
@adamgins that would be great. Please let us know. Happy New Years everyone!
