### ISSUE TITLE
The "Push.appCollection" is empty - No clients have registred on the server yet...

### ISSUE THREAD

**Issue by austingayler** [raix/push#153]
I'm following the basic tutorial, trying to get push notifs on my android device. What I have done:
* install raix:push@3.0.2
* configure my config.push.json file in the root directory
* create set the push methods  as well as allow anyone to send push notifications in pushMethods.js
* add a listener to for the client
* put my app on my-app.meteor.com
* run `meteor run android-device --mobile-server sharelift-core.meteor.com --production`

this outputs: 
```
...
=> App running at: http://localhost:3000/     
I20151122-12:59:19.097(-7)? Push.Configure { gcm: { apiKey: 'asdf' },
I20151122-12:59:19.098(-7)?   production: false,
I20151122-12:59:19.098(-7)?   sound: true,    
I20151122-12:59:19.099(-7)?   badge: true,    
I20151122-12:59:19.099(-7)?   alert: true,    
I20151122-12:59:19.099(-7)?   vibrate: true } 
I20151122-12:59:19.100(-7)? GCM configured    
=> Started app on Android Device.  
```
then when I execute the server notification in the console on my-app.meteor.com, and get the logs from that, it says:
```
[Sun Nov 22 2015 19:54:36 GMT+0000 (UTC)] INFO Push.Configure { gcm: { apiKey:
'asdf' },
production: false,
sound: true,
badge: true,
alert: true,
vibrate: true }
GCM configured
[Sun Nov 22 2015 20:03:36 GMT+0000 (UTC)] INFO Push: Send message "Hello" via query {}
[Sun Nov 22 2015 20:03:36 GMT+0000 (UTC)] INFO Push: Sent message "Hello" to 0 ios apps 0
android apps
[Sun Nov 22 2015 20:03:36 GMT+0000 (UTC)] INFO Push, GUIDE: The "Push.appCollection" is empty -
No clients have registred on the server yet...
```

I have also tried turning off wifi on my phone to test. What am I missing here?

**Comment by mvgalle** [comment]
Have you followed the instructions to configure the apn on Google developer
console?

**Comment by austingayler** [comment]
@mvgalle yes, I have

**Comment by austingayler** [comment]
In addition, `console.log('Push.id(): ' + Push.id());` in the client's Meteor.startup() outputs a valid id.

**Comment by raix** [comment]
using the `--mobile-server` flag on meteor?

**Comment by austingayler** [comment]
Yeah, I'm using that command. Pointed to my site on meteor.com. I pasted
the command I've been trying in my first post

**Comment by austingayler** [comment]
Does the package have any known incompatibilities?

`meteor list`:
accounts-facebook                1.0.6  Logi...
alanning:roles                   1.2.13* Rol...
aldeed:autoform                  4.2.2* Easi...
aldeed:collection2               2.3.1* Auto...
astronomerio:core                0.2.16* Eas...
blaze-html-templates             1.0.1  Comp...
check                            1.1.0  Chec...
dandv:jquery-rateit              1.0.22_2  R...
dburles:collection-helpers       1.0.3* Tran...
digilord:faker                   1.0.7  Fake...
ejson                            1.0.7  Exte...
fourseven:scss                   2.1.1* Styl...
houston:admin                    2.0.5* A ze...
iron:router                      1.0.9* Rout...
jquery                           1.11.4  Man...
logging                          1.0.8  Logg...
lukemadera:autoform-googleplace  1.0.7  Goog...
mdg:geolocation                  1.1.0  Prov...
meteor-base                      1.0.1  Pack...
meteoric:autoform-ionic          0.1.5  Ioni...
meteoric:ionic                   0.1.19  Ion...
meteoric:ionic-sass              0.1.9* Ioni...
meteoric:ionicons-sass           0.1.6* Ioni...
mobile-experience                1.0.1  Pack...
momentjs:moment                  2.10.6  Mom...
mongo                            1.1.3  Adap...
raix:push                        3.0.2  Isom...
random                           1.0.5  Rand...
reload                           1.1.4  Relo...
sanjo:jasmine                    0.20.1* Vel...
service-configuration            1.0.5  Mana...
session                          1.1.1  Sess...
spacebars                        1.0.7  Hand...
standard-minifiers               1.0.2  Stan...
tracker                          1.0.9  Depe...
twbs:bootstrap                   3.3.5* The ...
underscore                       1.0.4  Coll...
velocity:html-reporter           0.9.0* Reac...

**Comment by austingayler** [comment]
I had a coworker go through the tutorial using the same api key, and it worked with that, so it sounds like a compatibility issue.

**Comment by raix** [comment]
Odd - I'm not aware of any compatibility issues

**Comment by austingayler** [comment]
Pretty sure this was a compatability issue with Meteoric. I ported my app to Angular, and am using most of the same packages, and it got it to work in just a few minutes. So, I wouldn't worry about that considering Meteoric is no longer under development (and hasn't been for a few months). Cheers!
