### ISSUE TITLE
Push.send({}) not working in meteor + angularJS

### ISSUE THREAD

**Issue by mitiaptest** [raix/push#158]
@raix With meteor + AngularJS 

Push.send({
  from: 'Test',
  title: 'Hello',
  text: 'World',
  badge: 12,
  query: {}
});

Not working its throws 'Error: Match error: Expected g in field badge'.

We have tested this with  meteor simple example only added 
raix:push
angular

If we ran APP without angular package raix:push works but not sure why not working with angularJS.

This is working fine on browser but not in iOS and Android App.

If I remove badge from Push.send() then that work in iOS and Android App but not with badge.

@raix can you please help me on this ?

**Comment by raix** [comment]
sounds odd - not sure why it's expecting `g`

**Comment by mitiaptest** [comment]
@raix  This issue only with Android and iOS APP not with browser.

**Comment by mitiaptest** [comment]
[push_demo_with_angular_meteor_raix_push_issue.zip](https://github.com/raix/push/files/52272/push_demo_with_angular_meteor_raix_push_issue.zip)
@raix Attached is my sample project please help me.

Thanks,

**Comment by mitiaptest** [comment]
@raix Can you please help me on this?

**Comment by mitiaptest** [comment]
Facing this issue after updating ngular@1.0.7 to angular@1.2.2

**Comment by mitiaptest** [comment]
Resolved issue @raix created pull request for you.
https://github.com/raix/push/pull/161
