### ISSUE TITLE
push notifications overrides and redirecting 

### ISSUE THREAD

**Issue by Medhat-Khattab** [raix/push#160]
i'am using angular with  meteor
is there any way to prevent override the notifications ? 
and 
to redirect the user when click the notification to specific route

**Comment by raix** [comment]
not 100% sure what you mean. You can listen to `startup` or `message` events depending on what you want to do when the user taps a notifications to open the app or receives a notification while the app is open.

The events could trigger a change of route?

**Comment by Medhat-Khattab** [comment]
i am listening to startup and it's works well , thanks 

what about the another problem 
when i send two messages only the second one appears , overriding occur
there is a solution for that ?

**Comment by raix** [comment]
@Medhat-Khattab you have to read the docs but basically notifications are stacked - but you can change that behaviour

**Comment by Medhat-Khattab** [comment]
@raix : to be more clear i am asking about multiple notification ,what happened now with me is the server send the first one then override it at my menu bar i need to see the multiple notification

**Comment by raix** [comment]
it might be folding messages with same `collapseKey`?

**Comment by Medhat-Khattab** [comment]
thanks , it's finally works with me

**Comment by rashmimhatre100** [comment]
Hi @Medhat-Khattab are you able to redirect user to specific link in app.

**Comment by Medhat-Khattab** [comment]
@rashmimhatre100  : yes, added some details at message payload 
and then used it like that 
Push.addListener('startup', function(notification) {
  console.log(notification);
  $state.go(payload.goToView, {
    id: payload.id
  });
});
