### ISSUE TITLE
Does this package use / support the APN Feedback Service?

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#164]
While checking the documentation for APN, I stumbled upon this document:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW1

The second section describes a Feedback service that should be used regularly to check which devices could not receive their notifications after their time-to-live expired. According to this document, a provider (i.e. the Meteor app in our case) should regularly check this to prevent unnecessary notification sends, and this is monitored by APN.

Does ```raix:push``` or the underlying APN framework support this?

**Comment by raix** [comment]
yes - it should maintain the tokens by feedback from both gcm and apn

**Comment by derwaldgeist** [comment]
Thanks for your very fast reply!

**Comment by derwaldgeist** [comment]
BTW: I read in the ```raix:push``` newbie manual that this package only works if the server is deployed in the internet, not if it runs as localhost. Is there any special reason for that?

**Comment by raix** [comment]
It also works on localhost (thats how I do QA and development)
