### ISSUE TITLE
How does this package work as part of another package?

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#166]
If I use this package in the sample app, I get this message on the console
```
WARNING: Push APN is using development key and certificate
```
indicating that the package has initialized itself.

However, when I am trying to use the package with the very same config.push.json configuration in my real app, nothing happens. I also do not receive any messages there.

The difference is that my app uses ```raix:push``` not on the application level, but includes it as part of another package (for modularization reasons).

In my package.js file, I have included the package as:
```js
api.use('raix:push@3.0.2');
```

But this seems to be not enough to make it work. Is there any trick that has to be applied to make ```raix:push``` work as part of another package?

**Comment by derwaldgeist** [comment]
Update: I now tried to add ```raix:push``` directly to the app. This worked. But not if I am using it as a package, which I would prefer as this is more modular and re-usable.

**Comment by raix** [comment]
We use it via packages - you might have to add a dep in the app for configuration

**Comment by derwaldgeist** [comment]
Thanks for your reply. Yes, if I add it to the app, the configuration works. It's just a bit unusual that you have to do this.

**Comment by raix** [comment]
it's how meteor scopes variables
