### ISSUE TITLE
How to change the vibration and sound options on-demand?

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#169]
I would like to let the user decide if he wants to receive notifications with sound/vibration or not. So I would like to implement his as a user preference. However, the current raix:push configuration does require me to set these preferences once, in the json file. I've also seen that there's a deprecated Push.Configure(), but this may also be called only once.

Is it possible somehow to override / change this setting on-demand?

**Comment by mitiaptest** [comment]
@derwaldgeist vibration is working on iOS?

**Comment by derwaldgeist** [comment]
Not sure, my iPad does not have vibration. But on Android it works.

**Comment by mitiaptest** [comment]
Yes on Android it works but not for iOS devices.

**Comment by derwaldgeist** [comment]
In general, this option is more important for Android than for iOS. On iOS, you can set these options in the "message center", so there's no real need for an in-app option. But on Android, you can only switch them completely off or on in the app settings. And even this option is hidden somewhere deep in the settings.

**Comment by nddeveloper** [comment]
Same Issue here:
Any Helpppp.....

@derwaldgeist 

These are my config:

{ "apn": {
 "passphrase": "passphrase", 
"key": "PushChatKey.pem", 
"cert": "PushChatCert.pem" }, 
"production":false,
 "badge": true, 
"sound": true, 
"alert": true, 
"vibrate": true }

And I have sent notifications as below
Push.send({ from: 'Test', title: 'Hello',text: 'World', badge: 4, query: {}, sound: 'default' });

No Sound No Vibration Only badge working

**Comment by mitiaptest** [comment]
@ derwaldgeist  Agree, but its working on Android and not on iOS so for this we need to check the package or need to add any custom plugin ?

**Comment by derwaldgeist** [comment]
@nddeveloper: I had the same problem and - after some fiddling - found a workaround: You have to set ```sound: 'default'``` for APN only:

```js
Push.send({ 
  from: 'Test',
   title: 'Hello',
  text: 'World',
   badge: 4,
   query: {},
  apn: {
    sound: 'default'
  }
});
```
According to the docs, this should not be necessary, but it was the only way I got the sounds to work.

**Comment by derwaldgeist** [comment]
@mitiaptest: I don't understand exactly what you mean? As far as I can tell, the plugin currently used by raix:push would support a re-configuration of the settings on the fly.

**Comment by mitiaptest** [comment]
@derwaldgeist ok

**Comment by derwaldgeist** [comment]
Closing this since there was no progress.
