### ISSUE TITLE
Default sound is working on one Android device, but not on the other

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#170]
I am using 2 Android devices to test my app, a HTC One phone and a Nexus 7 tablet. On both devices, I've installed the app the same way and did not change the notification settings for the app on the device. Also, on both devices the volume is set to max.

But when I receive push notifications, the sound is only played on the HTC One. The Nexus 7 shows the notification, but remains silent. Since I am using the default sound, this can not be related to a non-working custom sound.

Do you have any ideas what might cause this?

I've also noticed that on the Nexus 7, the app's icon does not appear in the notification list (it's showing an empty icon), whereas on the HTC One the notification shows the app icon correctly, as it is on my iOS device.

**Comment by derwaldgeist** [comment]
Update: I just found out that the sound works on the Nexus 7, if I omit
```js
sound: 'default'
```
when sending the notification. Any ideas why this is not working?

**Comment by derwaldgeist** [comment]
Strange thing is: iOS *needs*
```js
sound: 'default'
```
You won't hear the sound if it is missing. So I had to use the overwrite
```js
apn: {
   sound: 'default'
}
```
to make it work on both Android and iOS. Don't think this is intended?

**Comment by mvgalle** [comment]
Hmm. You may want to do a custom sound for Android. Follow my post about playing custom sounds on android here. https://github.com/raix/push/issues/9 (see the reply under mvgalle).

**Comment by derwaldgeist** [comment]
Closing this, as I found a workaround.
