### ISSUE TITLE
badge number not shown on android

### ISSUE THREAD

**Issue by vohtaski** [raix/push#177]
Thanks a lot for this super nice plugin!

Everything was as expected on both ios and android except the badge on android.
But maybe I misunderstand something here.

I expected a number "7" appear in the right top corner of "my app" logo, when it's closed.
I get notification text but not the the badge number. I get this red number for ios app though.
Is it intended behaviour and I have to set it myself in `Push.addListener('badge')`
or it should be shown automagically?

push code:
```js
        Push.send({
            from: 'push',
            title: 'Some title',
            text: 'Some text',
            badge: 7,
            sound: 'airhorn.caf',
            payload: {
                title: title,
            },
            query: {
                // this will send to all users
            }
        });
```

cordova-android@4.0.0
raix:push@3.0.2

config.push.json:
```js
{
  //...
  "production": false,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true
}
```

**Comment by raix** [comment]
is badge count supported now by the android OS?

**Comment by vohtaski** [comment]
I don't think so, I thought your plugin sets it (similar to cordova-badge-plugin)?

**Comment by raix** [comment]
@vohtaski ok - nope - the push package uses the native behaviour - it's not present on android - the `cordova-badge-plugin` is as I recall kind of a hack.
I think it would make sense to add the badge feature in the cordova push package, since it provides the badge updates/api on iOS already.

**Comment by vohtaski** [comment]
yep, but it'd be indeed kind of a hacky solution, since android does not support it out-of-the-box through APIs. imho, for now we decided to skip this for our app ;)
so we can close the issue, unless you wish to change it into "feature request"

**Comment by raix** [comment]
@vohtaski I think it's a valid feature request - I'm just thinking if it's better suited for the cordova push plugin instead though :)

**Comment by vohtaski** [comment]
closing, submitted an issue on phonegap-plugin-push

**Comment by rashmimhatre100** [comment]
@raix Hi Sir, First of all thank you so much such a great plugin. As badges are supported now in android, do we have badges working for the same?
