### ISSUE TITLE
APN - Unable to push to connected devices from server

### ISSUE THREAD

**Issue by dennisharrison** [raix/push#18]
//config.push.json
```javascript
{
  "apn": {
    "passphrase": "AWESOMEPASS",  
    "key": "pushKEY.pem",
    "cert": "pushCERT.pem",
    "gateway": "gateway.sandbox.push.apple.com"
  },
  "production": false
}
```

//CLIENT init & alert w/ token
```javascript
Push.init({});
  Push.addListener('token', function(token) {
    if (token.apn) {
      alert('Got ios token ' + token.apn);
    } 
  });
```

//TEMPLATE EVENT
```javascript
Template.layout.events({
    "click .push-link": function () {
      Push.send({from: 'push',title: 'Hello',text: 'World',badge: 99,query: {}});
    }
  });
```
//SERVER init & Debug flag
```javascript
if (Meteor.isServer) {
  Meteor.startup(function () {
    Push.debug=true;
    console.log(Push.send({
      from: 'Test',
      title: 'Small message',
      text: 'Hello world',
      query: {} // Query the appCollection
    }));

    Push.allow({
        send: function(userId, notification) {
            return true; // Allow all users to send
        }
    });

  });
}
```

//CONSOLE OUTPUT
```
20150102-15:15:49.264(-6)? (STDERR) WARNING: Push APN is in development mode
I20150102-15:15:49.339(-6)? QFdPio68DGKawvCJ9
=> Meteor server restarted
I20150102-15:16:04.294(-6)? Push: Send message "Small message" via query {}
I20150102-15:16:04.296(-6)? Push: Sent message "Small message" to 0 ios apps 0 android apps
I20150102-15:16:34.304(-6)? Push: Send message "Hello" via query {}
I20150102-15:16:34.306(-6)? Push: Sent message "Hello" to 0 ios apps 0 android apps
```

//METEOR SHELL - Push.appCollection.find()
```javascript
{ _mongo: 
   { _connectCallbacks: [ [Function] ],
     _observeMultiplexers: 
      { '{"ordered":false,"collectionName":"_raix_push_notifications","selector":{},"options":{"transform":null}}': [Object],
        '{"ordered":false,"collectionName":"_raix_push_app_tokens","selector":{},"options":{"transform":null}}': [Object],
        '{"ordered":false,"collectionName":"meteor_accounts_loginServiceConfiguration","selector":{},"options":{"transform":null,"fields":{"secret":0}}}': [Object],
        '{"ordered":false,"collectionName":"photos","selector":{},"options":{"transform":null}}': [Object],
        '{"ordered":false,"collectionName":"users","selector":{},"options":{"transform":null,"fields":{"profile":1,"username":1}}}': [Object] },
     _onFailoverHook: { nextCallbackId: 10, callbacks: [Object] },
     _docFetcher: 
      { _mongoConnection: [Circular],
        _callbacksForCacheKey: {} },
     _oplogHandle: 
      { _oplogUrl: 'mongodb://127.0.0.1:3001/local',
        _dbName: 'meteor',
        _oplogLastEntryConnection: [Object],
        _oplogTailConnection: [Object],
        _stopped: false,
        _tailHandle: [Object],
        _readyFuture: [Object],
        _crossbar: [Object],
        _lastProcessedTS: [Object],
        _baseOplogSelector: [Object],
        _catchingUpFutures: [] },
     db: 
      { domain: null,
        _events: {},
        _maxListeners: 10,
        databaseName: 'meteor',
        serverConfig: [Object],
        options: [Object],
        _applicationClosed: false,
        slaveOk: false,
        bufferMaxEntries: -1,
        native_parser: false,
        bsonLib: [Object],
        bson: [Object],
        bson_deserializer: [Object],
        bson_serializer: [Object],
        _state: 'connected',
        pkFactory: [Object],
        forceServerObjectId: false,
        safe: false,
        notReplied: {},
        isInitializing: true,
        openCalled: true,
        commands: [],
        logger: [Object],
        tag: 1420233349176,
        eventHandlers: [Object],
        serializeFunctions: false,
        raw: false,
        recordQueryStats: false,
        retryMiliSeconds: 1000,
        numberOfRetries: 60,
        readPreference: [Object] },
     _primary: '127.0.0.1:3001' },
  _cursorDescription: 
   { collectionName: '_raix_push_app_tokens',
     selector: {},
     options: { transform: null } },
  _synchronousCursor: null }
```

On starting the app the iOS device alerts token, I can push to it via APN tester using the dev cert for this app ID.

How else can I debug this?

**Comment by idmontie** [comment]
I'm having similar issues on my end as well.  @dennisharrison are you using an APNs Developmen iOS certificate?

**Comment by raix** [comment]
Lets focus on the `Push.appCollection.find().fetch()` to see if any tokens have been registered on the server.
`Push: Sent message "Hello" to 0 ios apps 0 android apps` - this shows that the send command found no apps in `Push.appCollection`

**Comment by dennisharrison** [comment]
@raix Push.appCollection.find().fetch() is empty.  I've not taken insecure off of this project yet, so I figured it would register every device connecting?  Another message I got when trying to send a message from the server is:

```
W20150103-08:51:19.024(-6)? (STDERR) Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20150103-08:51:19.024(-6)? (STDERR)     at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
W20150103-08:51:19.024(-6)? (STDERR)     at EventEmitter.Push.send (packages/raix:push/lib/common/notifications.js:37:1)
```

So I tried changing this method to use this. instead of Meteor. - but I'm not sure that's helpful other than squelching the error?

```javascript
Push.send = function(options) {
  // If on the client we set the user id - on the server we need an option
  // set or we default to "<SERVER>" as the creator of the notification
  // If current user not set see if we can set it to the logged in user
  // this will only run on the client if Meteor.userId is available
  var currentUser = Meteor.userId && Meteor.userId() ||
          Meteor.isServer && (options.createdBy || '<SERVER>') || null;
```

@idmontie Yes, using a development specific certificate - reading through the longer issue about APN help here I see that one of the troubleshooting steps is to use a production certificate instead.  I'm not sure I'm to that problem yet though?   Shouldn't we see the collection updated either way since the device is grabbing a token anyway?

**Comment by raix** [comment]
@dennisharrison could you try the 2.4.1 version,

**Comment by dennisharrison** [comment]
OK, so that Push.send stuff on server is proper now it looks like:
```
I20150103-11:23:15.193(-6)? Push: Send message "Small message" via query {}
I20150103-11:23:15.199(-6)? Push: Sent message "Small message" to 0 ios apps 0 android apps
I20150103-11:23:15.201(-6)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
```
Still though when looking at Push.appCollection.find().fetch(), it's an empty array.

Digging around earlier I did uncomment:
```javascript
// XXX: should we do a test of the connection? It would be nice to know
        // That the server/certificates/network are correct configured

        // apnConnection.connect().then(function() {
        //     console.info('CHECK: Push APN connection OK');
        // }, function(err) {
        //     console.warn('CHECK: Push APN connection FAILURE');
        // });
        // Note: the above code spoils the connection - investigate how to
        // shutdown/close it.
```

The return was connection OK.  I've since recommended it, plus I just overwrote everything with your latest version from github.

As a sanity check, should I also look into using Push.sendAPN() to the device to make sure it works?  What is the syntax for APN, just a string?  Do you have an example of sendAPN I can dig up and modify to test that it's not a certificate issue?

Also, where should I look to try and debug why the client isn't trying to add itself to the collection?

**Comment by raix** [comment]
@dennisharrison The sendAPN and sendGCM is really internal api / advanced / deeper integration api - Its documented in ADVANCED.md - I would recommend that you get the client up and running (sending tokens to the server into Push.appCollection)

It should be enough to set credentials in `config.push.json` and use the `Push.send` command - this is the basics.

The idea is to depend on the appCollection for sending out notifications - its automatically maintained when services invalidates tokes etc. Its possible to add metadata to the appCollection data, still WIP but this will allow almost every thinkable usecase, still keeping the api isomorphic and simple (Push.setMetadata is implemented - but still in flux)

**Comment by raix** [comment]
@dennisharrison I did add the debug info `Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...` You gotta get the clients working before playing around on the server-side.

**Comment by raix** [comment]
Add the quick token test:
client.js:
```js
Push.addListener('token', function(token) {
  alert('Token: ' + JSON.stringify(token));
});
```

Btw. dont call `Push.init({});` ever :) Ive deprecated it in favor of the `config.push.json` file (Its replaced by `Push.Configure` but its again only for advanced use - it will throw errors if used with the `config.push.json`)

**Comment by dennisharrison** [comment]
I've taken out Push.init({}) - it will forever be banished :)

I get the alert with the proper apn token.  What does the options array need to look like to send a simple test message with Push.sendAPN()?

I'm using:
```javascript
Push.sendAPN("46459ee3026471cd990dd567b9}103aa01d0fe93560c92ace26b3dd6c1511e2da",{from:"test",title:"test messaage",text:"hello test",createdAt:new Date(),createdBy:"test"});
```

And I've got some logs in the sendAPN function to make sure that it's organized in the way I think it should be based on the other methods:
//userToken
```javascript
46459ee3026471cd990dd567b9}103aa01d0fe93560c92ace26b3dd6c1511e2da
```
//myDevice
```javascript
{ token: <Buffer 46 45 9e e3 02 64 71 cd 99 0d d5 67 b9 10 3a a0 1d 0f e9 35 60 c9 2a ce 26 b3 dd 6c 15 11 e2 da> }
```
//note
```javascript
{ 
	encoding: 'utf8',
	payload: { messageFrom: 'test' },
	expiry: 1420315204,
	priority: 10,
	retryLimit: -1,
	device: undefined,
	alert: 'hello test',
	badge: undefined,
	sound: undefined,
	newsstandAvailable: undefined,
	contentAvailable: undefined,
	mdm: undefined,
	compiled: false,
	truncateAtWordEnd: false,
	urlArgs: undefined,
	category: undefined
}
```
However, the message does not show on the device (I don't know what the expectation should be here).
I will leave the sendAPN alone for now and concentrate on getting the client in the collection.

Still the Push.appCollection.find().fetch() is an empty array for me.

**Comment by raix** [comment]
@dennisharrison the 2.5.0 got some bug fixes - I havent had the time to properly test this on android - but now it works (and added much better payload, its now consistent on both platforms and preserves types via ejson)

I'm not sure why the token isnt sent to the server - when the mobile app is started the server should log something like `Push: Got push token from app:`

**Comment by dennisharrison** [comment]
Updating to 2.5.0 - can you point me in the direction of the code that's supposed to update the server from the client?  Which method should do it?  I'm going to be poking around either way, but would appreciate any hints :)

**Comment by raix** [comment]
https://github.com/raix/push/blob/master/lib/client/client.js#L112
https://github.com/raix/push/blob/master/lib/server/server.js#L13

Im turning in for now

**Comment by dennisharrison** [comment]
@raix Thank you, I'll keep plugging away and see where I can get by tomorrow morning!

**Comment by adamgins** [comment]
@dennisharrison I have a todo to write up some help on dealing with certificates... sorry have not got there. Here's a short version that may help you debug this.. my guess is certificates are probably not configured correctly.

The general approach is get this working in development config, then once working swap to production. As per https://github.com/raix/push/blob/master/docs/IOS.md

For now just do it for development (so a subset of above) and you'll be using the config file with the development/sandbox settings. It seems like you have that covered, so I won't detail.

1) in Member Center create App ID with explicit option:
![image](https://cloud.githubusercontent.com/assets/7233741/5603712/56682d26-93e7-11e4-8139-8dc4131bee54.png)
 And Push on: 
![image](https://cloud.githubusercontent.com/assets/7233741/5603716/68806f6e-93e7-11e4-8f13-dabe802a49b1.png)

2) Edit that App ID and create a Development SSL Certificate. 
Go and create the PEM files as per instructions https://github.com/raix/push/blob/master/docs/IOS.md

3) Create a provsioning profile for iOS app Development
![image](https://cloud.githubusercontent.com/assets/7233741/5603752/a8217086-93e8-11e4-9f82-01b8a1fae27a.png)

Use the AppID from (1) above

4) run Meteor with your phone connected via cable. `meteor run ios-device --mobile-server http://<local ip of server>`

You should see them app open on your phone etc etc 

OK, so as per above it seems you have the Raix-Push stuff working and you see the token in the logs. Copy it.

Go grab one of the free (or paid) APN test tools - you can download from the OSX App Store. 

From here you should be to send a hardcoded Payload  . I use:
![image](https://cloud.githubusercontent.com/assets/7233741/5603776/a439c918-93e9-11e4-83c4-5d557ae2c16d.png)

You choose your certificates.

So, outside of the Meteor code you should be able to send your App a hardcoded notification. I found this helpful as it removed any issues in my code and validated the certificates were working. 

If this does not work, I am guessing something is messed up with either the SSL certificates or the provisioning profile.

**Comment by dennisharrison** [comment]
@raix I've got an alert right before: 
https://github.com/raix/push/blob/master/lib/client/client.js#L91

And I see it on the phone, but I've got a console log in:
https://github.com/raix/push/blob/master/lib/server/server.js#L14

And I don't see anything in the server console.  Any thoughts on how to figure out what's happening here?


@adamgins It's really good to see you in this issue, I read all the details of yours over and over so far :)
I can push directly to the device using APN Tester.  Thank you for the specifics on certificates and I think we should collect all the information we have and help Raix on the documentation front, I will have no issues doing that as soon as I can get this working!  Feel like I'm close at this point.

**Comment by adamgins** [comment]
Stoked!!! re: documentation - Go go for it. 

can you just add some extra `console.log` to see where it's going? .. assuming `Push.debug` has been set for the server.

**Comment by dennisharrison** [comment]
@adamgins I don't know where else to add the console log for this method!  I've added it in the very first line of the method, and I guess that means it's not being called?  How do you debug Metor.call not running the server method?

I have console logs after:
https://github.com/raix/push/blob/master/lib/client/client.js#L91

and after:
https://github.com/raix/push/blob/master/lib/server/server.js#L14

Push.debug is set - certainly.

I can send messages directly from the meteor shell by using Push.sendAPN() since setting the provisioning profile like you suggested! (!!!)

So, all I need to do now is sort out how to get this token inserted into the db - so close, oh so close, I can tell.

**Comment by raix** [comment]
@dennisharrison does the mobile app have connection to the meteor server? sometimes you have to set the `--mobile-server` flag in order for the mobile app to connect to the server.

```js
// Add the connection helper in the template {{connection}}
Template.hello.helpers({
  connection: function() {
    return Meteor.status().status;
  }
});
```

**Comment by dennisharrison** [comment]
@raix this could be the biggest 'duh' moment for me if you're right :)
I'm going to check for this right now, but I've been building the app / running the server using the --mobile-server <local ip>:port command.  Is it --mobile-server or --server?  Update this shortly.

**Comment by raix** [comment]
@dennisharrison Super - I think it would benefit the community with a step by step walkthrough - If you need a place for it we could create a markdown or add it in the wiki. (gist are ok for pure code - but some screen dumps would help too)

**Comment by dennisharrison** [comment]
@raix Yes, create the page you would like on the wiki and give me access or tell me where you want it and I'll add some screenshots too.

**Comment by raix** [comment]
I've added you guys as collaborators

You're welcome to edit / create pages etc. in the wiki - I've added a custom sidebar for better HOC - We could move the stuff in /docs folder into wiki too at some point.

(If you want to edit the code please create a dev/test branch keeping the master clean :) or clone and make pr's)

**Comment by dennisharrison** [comment]
Got it, working on the development APN writeup right now, stepping through another app to make sure I've got all the stuff right, then I'll do the production writeup.

**Comment by dennisharrison** [comment]
Steps I should have followed are here:  https://github.com/raix/push/wiki/iOS-Micro-Walkthrough

@raix Please feel free to close the issue - Thank you!

**Comment by raix** [comment]
Looks great @dennisharrison Thanks for the iOS writeup!

**Comment by adamgins** [comment]
Agreed - awesome job!!!
