### ISSUE TITLE
Push is working locally without deploy?

### ISSUE THREAD

**Issue by mikepaszkiewicz** [raix/push#186]
I was reading over one of the push guides, it mentioned that you need to deploy the app for the push notifications to come through? I've been working w/ push successfully in production and dev for several months and never had a problem receiving pushes locally.

It's super convenient not having to deploy to test, but not sure why I've been experiencing this behavior? I do have ngrok running to expose the port, but the build is pointing to localhost.

Mike

**Comment by raix** [comment]
you can run locally just fine - I don't remember any special settings or anything. But some networks might prevent some of the ports needed by the server.
