### ISSUE TITLE
Sent message to 0 ios apps 0 android apps

### ISSUE THREAD

**Issue by taxigy** [raix/push#187]
I'm having this `config.push.json`:

```json
{
  "apn-dev": {
    "passphrase": "qwe[]\\qwe[]\\",
    "key": "PushChatKey.pem",
    "cert": "PushChatCert.pem"
  },
  "gcm": {},
  "production": false,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true
}
```

The files PushChatKey.pem and PushChatCert.pem are stored in private/ folder in the Meteor project. The passphrase for the key is guaranteed to be correct.

I also have a server-side method and this little ad-hoc setup:

```javascript
Meteor.methods({
  sendPushNotification: function ({userId = this.userId, title = 'Hello', text = 'and welcome!'} = {}) {
    Push.send({
      title,
      text,
      from: 'push',
      badge: 14,
      query: {
        userId
      }
    });
  }
});

Push.debug = true;

Push.addListener('error', function (error) {
  console.error(error);
  console.error(JSON.stringify(error));
});

Push.allow({
  send: () => true
});
```

And I do simply the following:

```bash
$ meteor deploy xyz.meteor.com; meteor run ios-device --mobile-server xyz.meteor.com
```

And run the app from Xcode on the device. I accept receiving push notifications on that device.

I then open https://xyz.meteor.com in browser on a desktop device and, on the browser console, perform a server-side Meteor method call:

```javascript
Meteor.call('sendPushNotification', {}, (error, response) => console.log(error, response))
// undefined // <- return value
// undefined undefined // <- console.log'ged (because nothing is returned by the method by also no error)
```

And the result is

```
Settings userId "J5baP7xvbuTTX4KTk" for app: mytSJW2xrbKWRuGBZ
Send message "Hello" via query {}
Sent message "Hello" to 0 ios apps 0 android apps
```

one the console. And no push notification on the mobile device, even though I'm certain that `Meteor.userId()` would return proper value, i.e. `userId` as a parameter of server-side method and local user identity in the app instance on mobile device are identical.

Two points:

- as a newbie, I go through the newbie manual step by step and something is still missing, and
- for some reason, the app instance on the mobile device doesn't subscribe to push notifications, even though `Push.appCollection` seems to contain a single item that should represent this device.

Any ideas how to improve the doc and the process (and along the way, resolve the issue I am having, therefore help other raix:push newbies)?

**Comment by taxigy** [comment]
Okay, I think I figured out what was the problem. For some reason, the `Push.appCollection` collection retrieved data about the app at the second launch, _and_ the corresponding collection item received `apn` property with nested `token` property at the third app launch. Which is super weird but probably not specific to this package.

**Comment by creitz** [comment]
So, did you end up fixing this?

**Comment by taxigy** [comment]
To be honest, yes, and I couldn't reproduce the issue after that. It was probably a typical certificate issue. So this particular issue kind of isn't applicable to raix/push lib. Therefore closing it.

**Comment by creitz** [comment]
I ended up solving it too, and the two things I needed to do were 1) add
`+de.appplant.cordova.plugin.local-notification@0.8.4`
` +org.apache.cordova.dialogs@1.2.1`
 `+org.apache.cordova.vibration@2.1.1`

to .meteor/cordova-plugins, and 2)

export the corresponding private key, NOT the key show in the dropdown menu of the cert in keychain access.
