### ISSUE TITLE
Using raix:push and cordova:com.phonegap.plugins.facebookconnect

### ISSUE THREAD

**Issue by itaibs** [raix/push#192]
Hi!

I've [left a post](https://forums.meteor.com/t/using-raix-push-and-cordova-com-phonegap-plugins-facebookconnect/19730) on the Meteor forums as well, but so far no replies. I thought it might be more suitable here as it has to do directly with this package (and many thanks for this package by the way! It rocks :)).

The issue:
I'm working on a mobile Meteor app for both iOS and Android. In the app I need to have push notifications and for that I'm using raix:push and it's great.
I also would like the users to sign up to the app using their Facebook account and following this great guide, I have successfully made that happen on iOS.

The problem is that the above broke my Android build. I am now getting an error when trying to run on Android:

> UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexException: Multiple dex files define

Researching this online, it was easy to conclude that this is because of a clash between the two plugins in the title of this issue (and in fact if I remove cordova:com.phonegap.plugins.facebookconnect Android runs just fine).
AFAIU, this happens because cordova:com.phonegap.plugins.facebookconnect uses android-support-v4.jar and not v13, but I wasn't able to understand how to fix this issue from a Meteor app.

Since signing up using Facebook and using push notifications are both very common needs, I'm hoping someone else dealt with this issue successfully on Meteor before... Any help would be greatly appreciated!

Thanks.

**Comment by raix** [comment]
Hey @itaibs it sounds like theres a conflict between the two cordova plugins
It seems like its in the facebook plugin judging by https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1183#issuecomment-160279565

**Comment by itaibs** [comment]
Thanks a lot for the reply. I'll try to implement the solution in the link soon. I'm currently working on updating my app to use Meteor 1.3 so it'll probably take me a day or two to get to this. I hope it will be possible to implement this on Meteor, since it sounds like everyone on that thread is using Cordova directly and not via Meteor.

I'll post back with an update soon :).

**Comment by itaibs** [comment]
I forked the facebook plugin (seems like many others have done the same :)) and changed it as it says there. Things are looking good on Android now. I'll chek iOS as well soon and reports back.

Thanks a lot for the help!
