### ISSUE TITLE
Rarely receive the notifications

### ISSUE THREAD

**Issue by JacobPariseau** [raix/push#195]
It appears to send successfully, and the console reports that 0 iOS devices and 1 Android device have been sent the message, but maybe 1 in 10 of the notifications appear on my phone. The ones that do usually don't appear for five to ten minutes. Sometimes after I redeploy to Galaxy one of the notifications from before come through and pop up on my phone.

I'm running the latest official Meteor 1.3, deploying to Galaxy Developer with Compose.io Mongo. I am running the app on android with 

`meteor run android-device --mobile-server=http://app.domain.tld/ --verbose --settings settings.json`

I am sending the notification with this code directly from the browser console opened to my app in Galaxy

> title = "TITLE";
   text = "CONTENT";
   Push.send({
            from: 'kittens',
            title: title,
            text: text,
            badge: 1,
            query: {
                // this will send to all users
            }
        });

I track version numbers so I can tell when the hot code push has come through and verify that my static content is the same on both clients (web and android). If I deploy and then run on android immediately I usually get one or two notifications to appear within the minute I send them but afterward it's very unlikely they'll appear.

**Comment by JacobPariseau** [comment]
After disconnecting from Wifi and doing some research online, it seems likely that this problem is a combination of bad internet connection and the way GCM pushes messages. Messages appear to be slotted, such that when an application is first opened it can receive around 20 notifications max for a brief period, followed by single message slots opening up after seconds of silence.

Although unconfirmed, I am now convinced that the issues I have been experiencing are not caused by this package.

**Comment by raix** [comment]
can also be some restrictions on the wifi?
