### ISSUE TITLE
1.3+ Push.Configure server 'can't find keys' / APN acts like wrong environment

### ISSUE THREAD

**Issue by mikepaszkiewicz** [raix/push#206]
making the switch from mobile.config.json to Push.Configure/Assets.getText...not sure where i'm going wrong here, but am directly following the latest recommended syntax raix/push#203.

 in debug mode: the keys are getting read out + token is fetched and updated on the server logs, cordova log spits out push plugin success, and device asks permission. So basically the package does everything you'd expect, except on startup the server also logs:
```
ERROR: Push server could not find certData
ERROR: Push server could not find keyData
```
Digging deeper, it's running as if [this options parameter] (https://github.com/raix/push/blob/90d7ce94a37d6b25e45dcfda9f45769851b053c8/lib/server/push.api.js#L114) is missing the keys, which doesn't make sense because Push.debug literally reads them out to me right before I get the error. 

When I try and actually send out the notification, I get the usual 'send to token' and 'Push: Sent message "test" to 1 ios apps 0 android apps' alerts, then the apn node module blows up @ apn/lib/connection.js:224:10:

```
Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
```

I have quadruple checked all the usual suspects - production: false, debug:true, keys match and am in correct environment. all the other config values / pems worked fine and I ported everything from my mobile.config.json, which is no longer in the project. 

similar experiences or ideas?

**Comment by raix** [comment]
I've updated the readme on https://github.com/raix/push/tree/fix-device-dependency-deprecate-json-format - version `3.0.3-rc.2`

You can try to print the key on the server:
```js
// Reference to `/private/apnDevKey.pem`
console.log(Assets.getText('apnDevKey.pem'));
```

**Comment by mikepaszkiewicz** [comment]
cool thanks! so i bumped up the version, removed cordova-plugin-device@1.1.1 from my .cordova-plugins file, but getting an error that looks related to [this one on Meteor.](https://github.com/meteor/meteor/issues/5685) Made a fresh example project & cleared ~/.npm as suggested, got a new error on run ios-device. Any idea what this might be?

```
While adding plugin cordova:cordova-plugin-device@1.1.1 to Cordova project:
Cordova error: Failed to fetch plugin cordova:cordova-plugin-device@1.1.1 via git.
Either there is a connection problems, or plugin spec is incorrect

.meteor/packages/meteor-tool/.1.3.2_2.19gcch6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;

```

**Comment by raix** [comment]
bumped to `3.0.3-rc.3` - might have been a typo in the deps

**Comment by mikepaszkiewicz** [comment]
awesome that did it, thanks!
