### ISSUE TITLE
iOS Distribution Certificate expiration - one year anniversary!

### ISSUE THREAD

**Issue by Alveoli** [raix/push#215]
It's my one year anniversary with raix:push!  Thank you for the great work @raix et al! :dancers: 

So Apple has kindly emailed me to say iOS Distribution Certificate will expire.  Has anyone else come to the same threshold?

To resolve this, is it just a matter of generating and replacing the keyData and certData .PEM files?  And would the new PEMs work straightaway or do I have to wait for the old one to expire first?

**Comment by raix** [comment]
Thanks @Alveoli :)

You just need to create a new distribution cert and use that in the provision + generate new push certs...

**Comment by Alveoli** [comment]
Ok, I just did the Renew APN certificate dance, here's the difference from the first time:

1. Go to https://developer.apple.com/account/ios/identifier/bundle
2. Select your App
4. Edit. It should look like this:
![image](https://cloud.githubusercontent.com/assets/8811975/16061952/200a5f1a-3288-11e6-901c-8e8a8cbbdbb0.png)
5. Create Certificate
6. Continue
7. Choose your CertificateSigningRequest.certSigningRequest file from last year (You kept it handy, right? :) )
8. Continue
9. Download the .cer file
10. Follow the rest of the guide from _Congrats, now click 'Download'_ at https://github.com/raix/push/wiki/iOS-Micro-Walkthrough

Ultimately, replace your two exisiting .pem files.  You don't need to expire the old ones, so these ones can be valid at the same time. Note that the validity date is 365 days from when you request these new certs, so every time you're bringing your expiry date forward a little.

**Comment by Appuploader** [comment]
https://github.com/Appuploader/applicationloader/wiki/application-loader-windows
