### ISSUE TITLE
GCM specific style,  picture etc not showing

### ISSUE THREAD

**Issue by rajpa** [raix/push#232]
Hi raix - firstly thanks so much for this package..!

I have used mgp to install the 3.0.3-rc5 version of push.

I am able to get the notifications except for the gcm: {style} or gcm:{image} and summaryText. Even the gcm title is showing but not the rest. I must be doing something wrong that is simple. Can someone pls help?

Push.send({
  from: 'Test',
  title: 'Large icon',
  text: 'Remotely loaded',
  query: {userId : {$in : ["sPwFtSiNTDjGLMwbE"]}},
    gcm: {
    // gcm specific overwrites
    image: 'https://c1.staticflickr.com/9/8079/8391224056_96da82499d_n.jpg', 
     style: 'inbox', 
     summaryText: 'This is this.',     
     title: 'sent via gcm'
  }
});

**Comment by rajpa** [comment]
got it working with 3.0.2rc10!

just wanted to know if the "actions buttons" are implemented?

thanks!

**Comment by gsadhas** [comment]
I'm facing the same issue. Could you help me in this?

**Comment by rajpa** [comment]
@gsadhas Try the latest version. Should work

**Comment by gsadhas** [comment]
@rajpa Thanks for the help!  I download the latest version of raix/push 3.0.2 and I'm using Meteor 1.3.4.4. But I'm still facing the issue. Should I need to upgrade the Meteor version?

**Comment by rajpa** [comment]
@gsadhas you need to download 3.0.2-rc-10 or later from the github repository, not from atmosphere.

**Comment by gsadhas** [comment]
@rajpa It makes sense. I see the current (pre)release is 3.1.0. Let me try installing it from the github repo. Thanks again. I appreciate it!

**Comment by gsadhas** [comment]
@rajpa It works! I installed 3.1.0 pre release, Thank you for your help!

**Comment by raix** [comment]
(it was on atmosphere - anyways published now)

**Comment by raix** [comment]
finally even
