### ISSUE TITLE
"title" not showing in ios

### ISSUE THREAD

**Issue by PositronicBrain** [raix/push#241]
I am pushing the following kind of notifications:

     {
         title:  "CANONE RAI, MISE: MANCATO PAGAMENTO BOLLETTE LUGLIO CIRCA 10%",
         from: 'Public Policy',
         text: "Roma, 8 set - \"Il mancato pagamento dell",
         notId: 101,
         payload: {
                   "notificationId": "ad2342343aasdf", 
                   "url" : "/articles/uASDskMNGsFjFRrG9m" },
          query : {
             userId: "5YAkZ7dNAS4FXxuvw"
            },
      }

The notification title is showing correctly in android, but not in IOS devices where it is blank. Any hints?

**Comment by PositronicBrain** [comment]
It was a non issue, title is supposed to be the name of the app, which in IOS is set automatically

**Comment by andreasseiler** [comment]
@PositronicBrain I'm having the same problem here. As I understand there is a title in iOs which is called alert. How can I set this? For android the value in title is used as title. Can you give me a hint here?

Thanks,
Andi
