### ISSUE TITLE
Push token received but cant send notifications

### ISSUE THREAD

**Issue by MiGu3X** [raix/push#248]
So I'm doing a messaging app and when an user sends a message from the mobile/web platform it should send a Push notification with Push.send, but when i send a notification I'm getting this error

``` 
I20160921-00:14:14.080(-3)? Push: Send message "General" via query {}
I20160921-00:14:14.084(-3)? Push: Sent message "General" to 0 ios apps 0 android apps
I20160921-00:14:14.085(-3)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
```

**Client config**
```
Push.Configure({
  gcm: {
    projectNumber: projectNum,
  },
  android: {
    senderID: projectNum,
  },
  badge: true,
  sound: true,
  alert: true,
  vibrate: true,
  production: true,
});
```

**Sending a notification**
```
Push.debug = true;
Push.allow({
  send(userId, notification) {
    return true;
  }
});

export const Notifications = {
  send({ from, title, text, query }) {
    Push.send({
      from,
      title,
      text,
      query,
    });
  },
  sendAll({ from, title, text }) {
    Push.send({
      from,
      title,
      text,
      query: {},
    });
  },
};
```

**mobile-config.js**
```
App.configurePlugin('phonegap-plugin-push', {
  SENDER_ID: 'projectNum',
});
```

**/startup/server/push-configuration.js**
```
Push.Configure({
  gcm: {
    apiKey: Meteor.settings.private.gcm.apiKey,
  }
});
```
**.meteor/cordova-plugins**
```
cordova-plugin-device@1.1.1

```
`It seems nothing works... raix-push@3.0.2 , meteor 1.4.0.1 and having already `cordova-plugin-device@1.1.1` I've been searching all over the issues and I can't find how to fix it, thanks.

**Comment by MiGu3X** [comment]
Now I'm getting this errors
```
I20160921-12:19:43.966(-3)? A:Send message to: 'some_gcm_token'
I20160921-12:19:43.969(-3)? Push: Sent message "General" to 0 ios apps 1 android apps
I20160921-12:19:43.969(-3)? Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet...
I20160921-12:19:44.934(-3)? Unauthorized
I20160921-12:19:44.935(-3)? ANDROID: Result of sender is null

```

**Comment by MiGu3X** [comment]
Fixed by setting credentials with IP's on google cloud console
I used the IP of my mobile-server, 0.0.0.0/0 and 127.0.0.1

**Comment by rakeshashetty** [comment]
@MiGu3X : could you please explain the steps on how did you fix this. I am facing the same issue. I see the GCM token but message doesn't get delivered..

**Comment by MiGu3X** [comment]
> Fixed by setting credentials with IP's on google cloud console
I used the IP of my mobile-server, 0.0.0.0/0 and 127.0.0.1

I don't remember exactly what I did, but from that message I guess that on google developers console I added those IPs to the allowed ones.

**Comment by raix** [comment]
Should we put this in one of the guides?

**Comment by MiGu3X** [comment]
I don't know, this has over a year and I don't even remember what I did.
