### ISSUE TITLE
increment badge using +n

### ISSUE THREAD

**Issue by doubletaketech** [raix/push#25]
How do I increment the badge number in a send?  I tried +1 and '+1' and neither work.  If the badge is already 1 and then another message arrives, I need it to increment up by 1. 

'+1' gets rejected because it is a string.  +1 just sets it to 1 every time or has no effect.

Thanks,
Don

**Comment by raix** [comment]
We shoul prop let the send have a flag to do this pr default ?

**Comment by raix** [comment]
Tracking this in #45
