### ISSUE TITLE
Device not registering

### ISSUE THREAD

**Issue by miri-am** [raix/push#26]
My device (Ipad IOS 7.0) does not register or prompt to register push notifications. I followed the advice from the iOS Micro Walkthrough
- Tested cert and key (Verify return code: 0 (ok))
- set bundle identifier and provisioning profile in Xcode
- Deploy to name.meteor.com: 
```
meteor run ios-device --mobile-server name.meteor.com
```
- Device is connected to server as indicated by Meteor.status().status

Console says:
```
Push: APN configured
GCM configured
```
When sending via meteor shell:
```
Push: Send message "Congratulations" via query {}
Push: Sent message "Congratulations" to 0 ios apps 0 android apps
Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
```
Xcode output says:
```
PushPlugin.register: Push notification type is set to none
```
Any idea what could be the reason for not registering?

**Comment by nhatquang238** [comment]
+1

**Comment by miri-am** [comment]
Additonal info: it is working for Android devices.

**Comment by mvaisanen** [comment]
What happens if you add Push.addListener on the client? 
```
Push.addListener('token', function(token) {
	alert(JSON.stringify(token));
});
```

**Comment by miri-am** [comment]
@mvaisanen I have added this. Nothing happens...

**Comment by babakness** [comment]
Bump!

**Comment by Wenqer** [comment]
Bump!

**Comment by raix** [comment]
bumped to 2.6.1

**Comment by raix** [comment]
Closing this - similar to #33

**Comment by torayeff** [comment]
I also had this kind of problem. In my case I had placed config.push.json file in /server folder. So to fix that I have moved config.push.json to application root folder.

**Comment by torayeff** [comment]
I also had this kind of problem. In my case I had placed config.push.json file in /server folder. So to fix that I have moved config.push.json to application root folder.

**Comment by kymtwyf** [comment]
Hi I had the same problem in which message:" Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet..." shows . 

I finally find that I forgot to configure the Bundle identifier in Xcode: when was in General tab in the project profile. 

Hope it helps!

**Comment by chrise86** [comment]
I'm still having this issue, none of the above solutions work

**Comment by ethanteague** [comment]
Same here. Read every thread out there related to this issue (as it pertains to ios push), read all of the docs created by the project creators, ensured all of my xcode info matches up with what I have in the app and registered with Apple. The issue still remains. I'm going to explore some of the options discussed, here: http://stackoverflow.com/questions/22598009/how-can-one-send-ios-push-notifications-from-a-meteor-app

**Comment by chrise86** [comment]
@ethanteague I managed to solve this by adding the following to my `package.js`:

```jsx
Cordova.depends({
  'cordova-plugin-device': '1.1.1'
});
```

**Comment by ethanteague** [comment]
Thanks, @chrise86 - tried but it didn't work. Afraid this package is a no-go (for me).

**Comment by sahanDissanayake** [comment]
Same issue here

```
[52.38.112.15] Push: Send message "test" via query {}
[52.38.112.15] Push: Sent message "test" to 0 ios apps 0 android apps
[52.38.112.15] Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
```

**Comment by kaiyes** [comment]
same here. Tried everything for the last 6/7 hours. Getting the same message . I guess I gotta go for pusher or pushwush or something of that nature

**Comment by divu12321** [comment]
I'm stuck on this same issue. I've read all the threads about this but I never get prompted on my ios app to allow notifications. Below is my log:
`Push: Send message "checkout reminder!" via query { userId: null }
I20180205-15:55:41.856(5.5)? Push: Sent message "checkout reminder!" to 0 ios apps 0 android apps
I20180205-15:55:41.857(5.5)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
`
No idea where I'm going wrong.
