### ISSUE TITLE
Event listeners not working correctly

### ISSUE THREAD

**Issue by indesignlatam** [raix/push#267]
I have implemented listeners on an app but im not getting events on warm startup and on message or alert listeners.

I have the following listeners

```
Push.addListener('startup', (notification) => {
    // Called when message received on startup (cold+warm)
    if(!notification.payload){
        return;
    }

    if(notification.payload.flowrouter && notification.payload.flowrouter.route){
        const route = notification.payload.flowrouter.route;
        let params  = null;

        if(notification.payload.flowrouter.params){
            params = notification.payload.flowrouter.params;
        }

        FlowRouter.go(route, params);
    }
});

Push.addListener('message', (notification) => {
    alert(notification.message);
});

Push.addListener('alert', (notification) => {
    alert(notification.message);
});
```
- If the app was closed (cold) the startup event would be fired, but if the app was in background (warm) and open by tapping the notification, the startup event wont get called.
- If i have the app opened in foreground the message and alert events are not getting called.
- Im using raix:push@3.0.2 and meteor 1.4.2

Thanks in advance for any help.

**Comment by indesignlatam** [comment]
It only fails to trigger events on iOS android events work correctly.

**Comment by raix** [comment]
is it related to https://github.com/raix/push/issues/265 ?

**Comment by indesignlatam** [comment]
Its the opposite and adding that line didnt work. I recently tested a new build with test flight and seems to be solved. When the new build is in prod i will update this issue or close it.

Thanks @raix
