### ISSUE TITLE
advanced userid query

### ISSUE THREAD

**Issue by sirpy** [raix/push#27]
If setting the query to something like userId:{$in:[x,y,z]}, we get an error when server tries to save the notification request to the notifications collections (because in mongodb you can't have fields with dot or amp in them).
to fix this the server must first JSON.stringfy(query) and after reading it should JSON.parse(query)

**Comment by jonmc12** [comment]
This was helpful, to get that query to work, I had to create a local version of the package and I added this condition to lib/common/notifications.js:55:

```
if (options.query && options.query.userId && options.query.userId.$in){
     notification.query = {userId: JSON.stringify(options.query.userId)}
} else if (options.query) {
```

and I added this condition to lib/server/push.api.js:388:

```
      } else if (options.query && options.query.userId && (typeof options.query.userId == "string")){
      	options.query = {userId: JSON.parse(options.query.userId)};
        if (Push.debug) console.log('Push: Send message "' + options.title + '" via query', options.query);

        query = {
          $and: [
              options.query, // query object
              { $or: [
                  { 'token.apn': { $exists: true }  }, // got apn token
                  { 'token.gcm': { $exists: true }  }  // got gcm token
              ]}
          ]
        };
```

Kind of a hack, but lets me send push notifications to an array of user ids.

**Comment by raix** [comment]
Closing this tracking in #39
I've made a fix for this issue, can you guys give `raix:push@2.6.3-pre.1` a go to confirm if it's solving the issue?

**Comment by dennisharrison** [comment]
Works here!
