### ISSUE TITLE
How to debug Push? (Push simply stopped working.)

### ISSUE THREAD

**Issue by rajpa** [raix/push#279]
@raix Dear Raix,
My android app version of the meteor app has stopped receiving notifications. It was previously working well. Checked the GCM keys, changed them, checked the raix:push version, tried 3.0.3rc5+ and later 3.1.0pre1. Nothing works.

How do I debug this? Pls help. This comes at a time when I am pushing my app's first release to QA.

Thanks in advance,
rajpa

**Comment by rajpa** [comment]
I am guessing it has probably to do with FCM. Will try with the FCM keys and report back.

/rajpa

**Comment by rajpa** [comment]
My app is receiving FCM messages from the Firebase console but not from my server.

**Comment by rajpa** [comment]
@raix 
Dear raix,

I set Push.debug to true.

I get the following output:

Push.Configure { sendTimeout: 60000,
  gcm:
   { apiKey: 'AIzaSyAgHrtI.... ',
     projectNumber: 12345
     senderID: 12345
 } }
GCM configured
Push: Send worker started, using interval: 15000
Kadira: completed instrumenting the app
Push: Settings userId "mmybHMmpLEMvoridg" for app: fZDswqRNyxpDwso5m
Push: Send message "Large icon" via query {}
Push: Sent message "Large icon" to 0 ios apps 0 android apps
Push: Send message "Large icon" via query {}
Push: Sent message "Large icon" to 0 ios apps 0 android apps
Push: Send message "Large icon" via query {}
Push: Sent message "Large icon" to 0 ios apps 0 android apps

Pls help.

Regards/Rajpa

**Comment by rajpa** [comment]
more debug messages...

Create GCM Sender using "AIzaSyAg........"
A:Send message to: f2iBjEX20Gk:APA91bGnYd3OQXGY9hzki .......
Push: Sent message "Very Large icon" to 0 ios apps 1 android apps
Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet...
ANDROID: Result of sender: {"multicast_id":8110392525666500000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

why is there a mismatchsender id.. both the client and server are configured with the same senderid...

any help please?

**Comment by raix** [comment]
@rajpa I have to look into FCM and investigate - I'm sorry I don't have an answer atm.

**Comment by rajpa** [comment]
@raix strangely now, the push notification works for the first time . i.e. the app gets one push notification and then it stops working with the following error:

ANDROID: Result of sender: {"multicast_id":7730920622794207000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}
[ec2-52-66-65-175.ap-south-1.compute.amazonaws.com]Push: Send message "After Amma" via query { userId: { '$in': [] } }
Push: Sent message "After Amma" to 0 ios apps 0 android apps
3LGvYBH37KwRAufgD

**Comment by raix** [comment]
What version are you using?

**Comment by rajpa** [comment]
hi @raix, i am using  3.0.3-rc.7 as a local package cloned from this repo using mgp..

cheers
rajpa

**Comment by rajpa** [comment]
dear @raix, If I clear all the data in the app on android, it starts working again...!! It looks like the problem happens every time the app is autoupdated over hotpush...

**Comment by raix** [comment]
@rajpa hmm, so after a code push to android the push plugin stops working?

**Comment by rajpa** [comment]
@raix Suddenly everything is working again!! But I did have this problem a
while back. I cleared all the data from the Android app and it has
continued to work since then.

**Comment by raix** [comment]
@rajpa I think I had some issues on meteor and the code push once too - but I'm not sure if it's directly related to this package

**Comment by Denly** [comment]
Hi @rajpa The raix:push on my android suddenly not working too recently. May I know how to visit the firebase console to get the debug messages? I can't find the console on firebase panel to get debug information. Thank you!

**Comment by rajpa** [comment]
@Denly this happens to me whenever there is a version change in some of the cordova plugins of the app. then i clear the cache of the app and it starts working again.

regarding the firebase console, nothing appears on mine either!! 

@raix is it possible to view the stats of the push notifications on firebase?

**Comment by Denly** [comment]
@rajpa looks there is a way to view logs for diagnostics.  https://support.google.com/googleplay/android-developer/answer/2663268?hl=en

How you clear the cache? Like deleting .meteor/local/cordova-build & plugin-cache & bundler-cache? I did updated meteor recently. May be the cause.

**Comment by rajpa** [comment]
You have to clear the cache on the mobile.

**Comment by Denly** [comment]
@rajpa May I know how to clear the cache on mobile for meteor app? Sometimes my app doesn't run the code I just pushed. It'll help a lot. (even I uninstalled it)

**Comment by rajpa** [comment]
Go to application manager on android, click on the app and then app info
and clear cache..
