### ISSUE TITLE
basic example question / issue - 0 ios apps 0 android apps

### ISSUE THREAD

**Issue by funkyeah** [raix/push#28]
I am trying to get the basic example working:

In the server console I get: 
   
    GCM configured

I call a server side method to do the push:

     sendNotification: (beer) ->
        if Roles.userIsInRole(Meteor.user(), ["editor", "admin"])
            title = beer.name + ' is now on tap.'
            Push.send
              from: "Tin Whiskers Brewing"
              title: title
              text: "We've got one waiting for you."
              # badge: 12
              query: {}

and then in the console I get:

    Sent message "PushTest Beer is now on tap." to 0 ios apps 0 android apps

My config.push.json has what I belive to be the required fields:

    {
      "apn": {
        "passphrase": "XXXXXXXX",
        "key": "prodAPNkey.pem",
        "cert": "prodAPNCert.pem"
      },
      "gcm": {
        "apiKey": "XXXXXXXXXXXXXXXXX",
        "projectNumber": "32933758074"
      },
      "production": true,
      "sound": true,
      "alert": true,
      "vibrate": true
    }

Do I have to call something from the client to "register" device with the server or why might pushing to 0 devices be symptomatic of? There are a number of people with the app downloaded including myself.

Thanks for any help in advance!

**Comment by adam-hanna** [comment]
I think in your query, you need to include a userID. Or, if you want to send multiple, you can instead use

```javascript
tokens: array of appId's or tokens
```

**Comment by funkyeah** [comment]
@adam-hanna you are probably correct. Looking at it again I think maybe sending with 

    query: {} 

might be valid and send to all users (if I was using accounts and userIds). I am hoping not to make users have to sign-in to get push notifications since they are just simple updates.

So then as you mention tokens might be the way to go. I am not sure I understand what the correct way to go about that is. Looking at the issue you filed it looks like you use Push.addListener on the client and server to set/update a token by inserting/updating the user profile. Would I just then make a collection to store all registered tokens in or is there a better way?

**Comment by adam-hanna** [comment]
The user will have to sign in at least once in order to generate a token. Tokens are generated by apple and google. It's how they know who to send push notifications to. You should definitely store these somewhere. I store them in my user document, but the raix:push package also has a collection that is used for storage as well.

**Comment by funkyeah** [comment]
While I think adding accounts might fix the issue I don't think having accounts is supposed to be absolutely necessary to do push notifications. If you provide a blank query then as far as I can tell its just supposed to match all tokens stored in appCollection.

I'm a terrible programmer so forgive me if none of this makes sense but my reading of the code makes me believe those tokens should still be pushed into appCollection regardless of the use of the [accounts base](https://github.com/raix/push/blob/master/lib/client/client.js#L4) package.

I think that the problem may lie in the fact that the client side [Push.Configure](https://github.com/raix/push/blob/master/lib/client/browser.js#L28) is the only thing that calls [initPushUpdates(options.appName)](https://github.com/raix/push/blob/master/lib/client/client.js#L109) which in turn calls [reportTokenToServer ] https://github.com/raix/push/blob/master/lib/client/client.js#L77). So if I don't do Push.Configure on the client side the token never get reported to the server.

Maybe this could have something to do with the funkyness you experienced with push.config.json in your issue?

@raix does what I say above actually make any sense?

**Comment by raix** [comment]
I havent read it all but you can pin clients on Push.id() instead of user id - you can also just add metadata and query that. Its pretty flexible, unfortunately I havent time for support/documentation at the moment - feel free to pr wiki and readmes

**Comment by raix** [comment]
Tracking this in the Doc team issue, closing this
