### ISSUE TITLE
APN token lost in production. 

### ISSUE THREAD

**Issue by floor12** [raix/push#288]
I have a very strange behaviour of push plugin.
When server runs on the local host everything is fine: ios devices are registering with token and all run greats.
But in production server (on galaxy cloud), when you are trying to send a notify, device apn token is removing from _raix_push_app_tokens collection and notify is not not sending.

When im restarting app on device, token updates  in database again. 
![2017-04-01_11-22-07](https://cloud.githubusercontent.com/assets/8406969/24577417/ab197210-16cd-11e7-82a5-468e3ce1f316.png)

Token presents.
![2017-04-01_11-21-38](https://cloud.githubusercontent.com/assets/8406969/24577419/b165704c-16cd-11e7-9c54-6715f8167017.png)

Sending one notify and token disappearing from db **without any debug messages in console**.

![2017-04-01_11-22-27](https://cloud.githubusercontent.com/assets/8406969/24577426/bdd63122-16cd-11e7-8d4a-279287317280.png)

It happens in production and dev modes only on remote production server.

**Comment by floor12** [comment]
it was solved by meteor updating and synchronization of server and client version

**Comment by floor12** [comment]
No... i cant understand whats is wrong 8( but tokens removed from database

**Comment by floor12** [comment]
my fault. i have few instances running in the galaxy cloud. 8(

**Comment by pptoan23** [comment]
I have same problem with GCM token. But I use Meteor 1.2 for production, I can't update Meteor version. Have you any solution without Meteor updating? @floor12 
Thank you!

**Comment by floor12** [comment]
@pptoan23  this was a stupid problem )  a few app instances was running in the same time and working with the same DB.

**Comment by pptoan23** [comment]
Did you mean raix:push is not thread-safe? How did you fix your problem?
I am using micro services and they are working with the same DB.
