### ISSUE TITLE
iOS device tokens gets deleted

### ISSUE THREAD

**Issue by ianpogi5** [raix/push#303]
Thank you @raix for this module and it has been working for years.

Unfortunately since a week ago, for some reason iOS device tokens gets deleted if I send push notifications for at least 3 consecutive times. Thus only the first one or two notification gets received. Then any succeeding notification will never be sent because the token has been deleted. Killing the app and opening it again will restore the token. Any idea why this happens?

**Comment by Wade-BuildOtto** [comment]
This is happening to me as well, Were you able to fix this? and closing and re-opening the app does nothing.

**Comment by ianpogi5** [comment]
It was a newly setup app which has a wrong ssl certificate.
