### ISSUE TITLE
Meteor 1.5 / push@1.10.4 / raix:push@3.0.2 - cant get an app token / collection empty

### ISSUE THREAD

**Issue by Wade-BuildOtto** [raix/push#308]
I can't seem to get the phone to register at all. I am running on the latest meteor and cordova plugins, I am unable to roll back raix:push its coming up incompatible with the most recent version. 

I am running it on galaxy it registered once but then the token disappeared, and now it wont register again, I have nearly everything else working this is the last thing. 

Any ideas?

--
raix:push@3.0.2
--
cordova-plugin-device@1.1.6
phonegap-plugin-push@1.10.4

new version in the works:
phonegap-plugin-push - v2.0.0-rc5 (2017-06-20)

**Comment by tenshis** [comment]
Any progress here?

**Comment by Wade-BuildOtto** [comment]
apple changed a bit, you need to setup and enable on developer.apple.com and enable it on xcode separately, they use to be tied together, once they were both setup and enabled it worked fine.

**Comment by raix** [comment]
Do we need to add this in the iOS guide?
