### ISSUE TITLE
cumulative notifications

### ISSUE THREAD

**Issue by batcode007** [raix/push#317]
I am developing a meteor app with version meteor version 1.6. I added the raix:push package and its sending notifications as desired. Now if more than one notification is sent, I want it to be displayed as an inbox, whereas as of now, if more than one notification is sent, the new notification overlaps on the previous one. 
I tried using this :  
                                     
                       `Push.send({

					from: 'appName',

				 	title: 'New notification',

				  	text: 'test',
				  	badge: 1234                             //random four-digit number

				  	gcm: {
					    style: 'inbox',

					    summaryText: 'There are many notifications'
  					},
				  	query: {
				    	userId: user.userId,
				  	}
				});`
But it doesn't work. I have tried using payload too but the result was the same.

**Comment by VioletaCalvo** [comment]
You have to set the `notId` for each notification as detailed in [ADVANCED.md](https://github.com/raix/push/blob/master/docs/ADVANCED.md#display-multiple-notifications-on-android) documentation

**Comment by batcode007** [comment]
If notId is not set then the Push plugin defaults to a value of 0 causing each message to overwrite the previous and only ever display a single notification
