### ISSUE TITLE
Errors prevented bundling: While loading plugin `configuration`?

### ISSUE THREAD

**Issue by awgust-taylor** [raix/push#328]
Greetings @raix can you tell me why my build process is failing?
I don't know about the other guys who are having issues but "use strict"; fixed my testing on development.
But now I am trying to make a build and it keeps failing, I have been looking everywhere for an answer to no avail, do you have any idea why not working?
Thanks in advance

Errors prevented bundling:
While loading plugin configuration from package raix:push:
vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet
supported outside strict mode
at Object.exports.createScript (vm.js:24:10)
at /tools/fs/files.js:1161:34
at Function.time (/tools/tool-env/profile.js:305:10)
at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
at /tools/isobuild/bundler.js:1936:15
at Array.forEach (native)
at Function..each..forEach
...........

**Comment by awgust-taylor** [comment]
Sorry guys Raix might be busy, has anyone else experienced this issues or know how to fix it? Thanks

**Comment by raix** [comment]
@awgust-taylor sorry about the lag - do you have "ecmascript" package added in your project? what version of meteor are you on?

**Comment by awgust-taylor** [comment]
greetings @raix I am sorry I did not know you replied to me but I do thank you in again for taking the time too. I am still suffering from that block. I on meteor version 1.8.1 and yes I do have the ecmascript package added as ecmascript@0.8.2.

**Comment by joshua-seertech** [comment]
Hi i know this is closed, but how was this resolved?  @awgust-taylor

**Comment by joseiramrj** [comment]
Hi i know this is closed, but how was this resolved? @awgust-taylor

**Comment by joshua-seertech** [comment]
Hi this is fixed by:
meteor update
meteor npm install @babel/runtime
