### ISSUE TITLE
No tokens in Push.appCollection

### ISSUE THREAD

**Issue by mvaisanen** [raix/push#33]
I followed the basic example. When trying to Push.send() via Meteor shell:
```
Push.send({
  from: 'Test',
  title: 'Hello',
  text: 'World',
  badge: 12,
  query: {}
});
```
It fails. Here is the terminal output.
```
=> Started app on iOS Device.                 
=> Started MongoDB.                           
W20150123-11:49:30.537(2)? (STDERR) WARNING: Push APN is in development mode
=> Started your app.

=> App running at: http://localhost:3000/
I20150123-11:57:15.575(2)? Push: Send message "Hello" via query {}
I20150123-11:57:15.583(2)? Push: Sent message "Hello" to 0 ios apps 0 android apps
I20150123-11:57:15.588(2)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
```

When I added Push.addListener() to client side, I got an alert with correct token.

```
  Push.addListener('token', function(token) {
    alert(JSON.stringify(token));
  });
```
If I find objects in the collection via Meteor shell. It's empty.

```
> Push.appCollection.find().fetch()
[]
```

Here is the xcode console output
https://gist.github.com/mvaisanen/f42b27f9c55fae802863

And here is the full repo:
https://github.com/mvaisanen/SimplePushApp

**Comment by raix** [comment]
did you set the `--mobile-server`?

**Comment by mvaisanen** [comment]
Yes, meteor run ios-device --mobile-server 192.168.1.6:3000

**Comment by mvaisanen** [comment]
I tried to use raix:push-update method like this:
```
Push.addListener('token', function(token) {
	alert(JSON.stringify(token));
	Meteor.call('raix:push-update', token, function(err, result){
		if (err) {
			console.log("ERROR: I am inside raix:push-update call")
		} else {
			console.log("Succesfully added: " + result)
		}
	});
});
```
But nothing was inserted. Neither error nor success message was logged to console.

**Comment by mvaisanen** [comment]
Is there any simple and working ios example apps on github or somewhere else which I could clone?

**Comment by nschulte** [comment]
I'm also having this issue. My code is copy-pasted straight from the base example (filling in my keys). Can anyone give a full working example? I'm not confident I have the correct IP whitelist on my Google API. I have an app with a custom domain hosted on Meteor.

**Comment by nschulte** [comment]
I'm having this issue except on with gcm and I'm not getting any tokens. Would be really nice to have a simple working repo to work off of.

**Comment by insaneinc01** [comment]
Pretty much the same issues.. Everything works as mentioned, but the device won't get registered. Push.appCollection is always empty.

Could someone post a working repo (for iOS) please??

**Comment by lukemadera** [comment]
+1

**Comment by wrannaman** [comment]
+1

**Comment by raix** [comment]
Closing this as its a matter of better docs - tracking it in the Doc team issue

**Comment by dantsai** [comment]
I know this is closed with 'better docs' being the solution.. but in the meantime, how does one fix this? I'm having trouble sending a notification to my iPhone and am running into this very issue

Thanks

**Comment by jracollins** [comment]
I had this same problem and the solution is after running `Meteor run` is to ensure that both the bundle ID and the provisioning profile in the Xcode build settings are the same as your App ID in Apple developer center. My Xcode was defaulting to "automatic" provisioning profile, and was not choosing correctly. It should all work after this.  

Its in the docs as a required step but can be missed - think this is the most likely culprit for this `The "Push.appCollection" is empty` issue.

**Comment by pramodrwt** [comment]
+1

**Comment by raix** [comment]
If one of you can do a pull request on the docs - I'm not fully into the details on this one - just edit the markdown directly on github
