### ISSUE TITLE
I want to pass a custom field in Push.send and read it in Push.addListener

### ISSUE THREAD

**Issue by batcode007** [raix/push#330]
I want to send an id via Push.send and then read it when user clicks on the notification. Is it possible?

**Comment by mikiand** [comment]
i need the same functionality, how can i add custom url in Push.send()  and then on notification tap to catch event in eventListener so i can navigate to proper location on the app when the app is in background. Can someone provide sample!? is that payload is used for? Please give us a hint, there is no documentation about that functionality that is commonly used?!
