### ISSUE TITLE
Does this package still work for native push notifications on Android?

### ISSUE THREAD

**Issue by occasl** [raix/push#332]
I've used this package in the past when Android was GCM, but now they switched to FCM and my developer was telling me it will only work for in-app messaging, meaning the app would have to be in the foreground to receive a push notification. That isn't push notifications the way I see it. Can you please advise?

**Comment by laa99** [comment]
Yeah I tried using this package and I was wondering if this package is still being maintained. :/

**Comment by occasl** [comment]
We switched to FCM and got it working with the latest version of this package. Can't say to what extent this package is maintained, but it works fine for us given current mobile environments.

**Comment by hridayeshgupta** [comment]
@occasl i just started using it and couldn't get notification working on meteor app on android. I am not getting token callback, and don't know(cant find in documentation) what function would trigger asking permission for notif on android then trigger token callback. can you share relevant code sample for this for latest version? Thanks
