### ISSUE TITLE
Where should the files be stored

### ISSUE THREAD

**Issue by vertangelx** [raix/push#34]
I'm starting out using this package, so this is quite confusing to me. When configuring `config.push.json`...

1. Where do you place the apn key and cert .pem files? I'm assuming some places are not suitable as the key must be in a secure location.

2. Where do we place the file `config.push.json`, since it contains the apn passphrase

**Comment by raix** [comment]
in `myApp/private`
`config.push.json` in app root `myApp`

**Comment by raix** [comment]
Closing this as documentation improvements are tracked in a special issue, thanks
