### ISSUE TITLE
no notifications in android oreo

### ISSUE THREAD

**Issue by batcode007** [raix/push#340]
Hi, 
#334 
@raix 
@FelixOBrien

Apparently we need to have a channelId associated with each type of notification for android 8 and above. 

Meteor version : 1.7.0.3

raix_push version : 3.3.0

My push object is as follows : 

    Push.send({
			from: '',
			title: title,
			text: text,
            NOTIFICATION_CHANNEL_ID : '45664',
			android_channel_id	: '12chdt09',
			channel_id : '79',
			CHANNEL_ID : '81',
			channelID : '123',
			notId : nId,
			gcm: {
				title: title,
                NOTIFICATION_CHANNEL_ID : '45664',
				channelID : '123',
				android_channel_id	: '12chdt09',
				channel_id : '79',
				CHANNEL_ID : '81',
				style:  'inbox',
				summaryText: 'There are %n% notifications '
			},
			payload : {
				id : id
			},
			query: {
				userId: {
					$in: userIds
				},
			},
			"time_to_live" : 2419200
		});

I have tried inserting channelId in various ways mentioned above but no positive result yet. Any help?

**Comment by rashmimhatre100** [comment]
Any breakthrough?

**Comment by batcode007** [comment]
you can refer to this https://github.com/raix/push/issues/341
