### ISSUE TITLE
Mongo primary election results in stopped delivery

### ISSUE THREAD

**Issue by geekgonecrazy** [raix/push#343]
If you are running a multi-node mongo cluster and then the primary node steps down, the raix:push package stops sending notifications.

To resolve you have to restart the meteor app and then it will notice all of the items in the queue and rapidly send them out.

My suspicion...

The sendWorker is in the middle of sending when the election happens and this mongo query fails: https://github.com/raix/push/blob/master/lib/server/push.api.js#L685

Resulting in this: https://github.com/raix/push/blob/master/lib/server/push.api.js#L673 still equaling true.  So it never attempts to send a notification again.

**Comment by sampaiodiego** [comment]
I have published a forked version with the fix https://atmospherejs.com/rocketchat/push repo at https://github.com/RocketChat/push
