### ISSUE TITLE
Better documentation for how to play a sound

### ISSUE THREAD

**Issue by cwohlman** [raix/push#36]
It wasn't obvious to me how to play a sound on ios, here's the requirement:
1. Place your sound in `public/`, e.g. `pubic/beep.wav`
2. Reference your sound by including `www/application/` e.g. `www/application/beep.wav`

**Comment by raix** [comment]
Hmm, the sound referece should be the same in the api (paths could be off?)
https://github.com/raix/push/blob/master/lib/client/cordova.js#L117
https://github.com/raix/push/blob/master/lib/client/cordova.js#L76

I'll take pull requests if your up to it :)

**Comment by cwohlman** [comment]
Maybe I'm using an older version of the plugin, let me check that first
before I suggest any changes to the documentation.

**Comment by cwohlman** [comment]
Well I updated to the latest version, but I'm still a little confused.

When is `onNotificationAPN` called? I'm currently using the push
notification api like so: `sound: "www/application/audio/alarm.wav"` if the
code you referenced is being called that would seem to result in the
unlikely filename `application/www/application/audio/alarm.wav`.

(I'm using `Push.send` to send notifications)

**Comment by raix** [comment]
I haven't been using the sound part myself - so its something worth investigating/testing/documenting
The onNotification is called on in app notifications - I'm not 100% sure about playing sounds on notifications when the app is in background or closed. But theres a difference there I think.

If we can trigger sound on closed apps its prop. the native sounds?

**Comment by cwohlman** [comment]
Audio notifications definitely work differently, I've figured out how to
send audio messages using this format:
```
        Push.send({
          from: "MyApp",
          title: fromUser.displayName(),
          text: doc.message,
          badge: 1,
          sound: doc.safetyConfirmation ? "www/application/audio/alarm.wav"
: "default",
          query: {
            userId: doc.toId
          }
        });
```

**Comment by raix** [comment]
I agree that better documentation would be nice on this area - I haven't actually tested or used sound in my apps yet, so you guys are prop. better at it than me.

I'm closing this issue but referencing it from the Doc issue
