### ISSUE TITLE
Use with server only

### ISSUE THREAD

**Issue by lucnat** [raix/push#362]
I have a meteor server to which some apps are connected through a REST API. I would like to use this package to send push notifications to users (which are regular meteor accounts). Since there is no meteor client in this situation, how can this package be used?
What information from a user's phone do I need to register the device (which I do on the server), so that I can send push notifications to that user?

**Comment by shivang007** [comment]
You can use this package, the only thing you will need is their userId.

**Comment by shivang007** [comment]
If you mean there are separate apps to which you want to send notifications, then you will need to run separate servers for each app, which will have their unique certificates (GCM/FCM/APN).
