### ISSUE TITLE
Documentation for iOS

### ISSUE THREAD

**Issue by fazilboudjellal93** [raix/push#368]
hello I have followed the doc for set the push notification in iOS but I got many diffuclity since apple made the key_file to .p8 is there any updated trick to convert the p8 file to .pem?

**Comment by shivang007** [comment]
Follow [these](https://gist.github.com/kublaios/f01cdf4369c86ddd6d71) steps.

**Comment by fifou17** [comment]
@shivang007 I did but the problem is apple changed the authkey.p12 to authkey.p8

**Comment by fazilboudjellal93** [comment]
nvm i solved it

**Comment by shivang007** [comment]
@fazilboudjellal93 Glad to hear that! If it was a special case and you think majority will face the same, you are welcome to submit a merge request specifying it in our docs :)
