### ISSUE TITLE
Going back to the action buttons

### ISSUE THREAD

**Issue by atomoc** [raix/push#374]
I did it based on the instructions for this plugin and tried the phonegap-plugin-push instructions. Functions do not start at all; instead, the following is displayed in the console:

![image](https://user-images.githubusercontent.com/465108/77143414-4bf0d580-6a94-11ea-8aff-7a66de9730bb.png)

**Comment by atomoc** [comment]
Checked in meteor version 1.9 and 1.10

**Comment by atomoc** [comment]
Rummaged the entire Internet, I will be very grateful for any support

**Comment by shivang007** [comment]
@atomoc The Action buttons seems broken in latest versions!
Will get back to you on this.

**Comment by atomoc** [comment]
Still, the option from the [documentation](https://github.com/phonegap/phonegap-plugin-push/blob/2f45c0dd7520da1f6bb4b86c15c747dec0cfef1c/docs/PAYLOAD.md#action-buttons) for phonegap-plugin-push helped, the actions work.

Now I'm trying to solve the problem with forceStart: 1 и foreground: false. I just can’t figure it out. It seems that the documentation is written here before the implementation of the relevant functions.

**Comment by atomoc** [comment]
Added `App.setPreference('KeepRunning', 'true');` to file **mobile-config.js** and it worked!

**Comment by shivang007** [comment]
It was implemented, but during the time I added Action buttons to Raix-Push, we were on 1.8.4 of phonegap-plugin-push, after which Push broke for Android 8 and we made the necessary changes for that. During this process, Action buttons functionality was untested for the latest devices.

Nevertheless, glad to hear it works for you!
Do you mind specifying your versions? I will update the documents with necessary changes.

**Comment by atomoc** [comment]
phonegap-plugin-push@2.3.0
cordova-plugin-device@2.0.3
METEOR@1.10.1
raix:push@3.4.1

**Comment by atomoc** [comment]
No solution for the icons? No matter where I put the images, nothing happens.

**Comment by atomoc** [comment]
android/res/drawable, android/app/src/main/res/drawable, android/app/src/main/assets/www/application/app...

**Comment by shivang007** [comment]
Try
cordova-build-override/platforms/android/app/src/main/res/raw/

**Comment by atomoc** [comment]
yes, I tried all the way through cordova-build-override
