### ISSUE TITLE
Open SSL Verify Return Code Error Solved | Add to iOS-Micro-Walkthrough

### ISSUE THREAD

**Issue by wrannaman** [raix/push#41]
This would be helpful to add to the https://github.com/raix/push/wiki/iOS-Micro-Walkthrough. 

Answer based on:
http://stackoverflow.com/questions/23343910/is-this-an-error-verify-errornum-20unable-to-get-local-issuer-certificate

Problem: 
When executing the following command:
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem

I was getting this error: 
![screen shot 2015-03-06 at 7 47 13 am](https://cloud.githubusercontent.com/assets/5325165/6528179/26d244b6-c3d5-11e4-832f-61cf821f6dc6.png)

Solution:
Go to : https://www.entrust.net/downloads/root_request.cfm
Download the file : 
![screen shot 2015-03-06 at 7 48 50 am](https://cloud.githubusercontent.com/assets/5325165/6528205/4804dbbc-c3d5-11e4-84f4-4f0d641d5ec6.png)

Place it in the same location as your cert and key. 
Use the following command:
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -CAfile entrust_2048_ca.cer -cert cert.pem -key key.pem

Results in:
![screen shot 2015-03-06 at 7 50 13 am](https://cloud.githubusercontent.com/assets/5325165/6528230/708920a2-c3d5-11e4-91ca-c03bd7c19242.png)

**Comment by raix** [comment]
Thanks @wrannaman this is stuff we need in there, if you are up to it I would take a pull request,
*adding reference to this issue on the doc tracking issue #44 and closing this*

**Comment by guillim** [comment]
https://www.entrust.net/downloads/root_request.cfm -> 404 file not found :(
