### ISSUE TITLE
Callback not invoked when in background mode

### ISSUE THREAD

**Issue by giggioz** [raix/push#42]
Hi folks,

moving some steps forward with this package : now i'm able to correctly send push notification to an android device, when my app is in foreground everything works fine and the following listener is called

```
Push.addListener('message', function (notification) {
        console.log(JSON.stringify(notification));
        Dialogs.alert(notification.message, function(){}, notification.payload.title, 'OK');
    });
````

Dialogs is a meteor package :

*hybrid:dialogs             1.0.3  Cross-platform dialogs: alerts, confirms, and prompts (Cordova).*

**Unfortunatly when my app is in background i still receive the notification on the status bar but when i tap on it and my app pops in foreground the above callback is not called.**

I did some googling and found this interesting post

http://stackoverflow.com/questions/24234944/cordova-push-plugin-callback-not-invoked-when-the-app-is-in-background

extracting the best suggestions from there i tried:

-  [...] I had to clear the dalvik cache and restart my phone. Happened to me twice so far. Seems to a known issue in android, https://github.com/phonegap-build/PushPlugin/issues/35.

- [...] I had a similar issue with Cordova 3.5.0 and PushPlugin 2.2.0: notifications worked when the app was in the foreground but not when it was in the background or not running. I found the solution by reading the source code of PushPlugin (file src/com/plugin/gcm/GCMIntentService.java): the notification's payload must include "message" and "msgcnt" keys.

but none seems working for me.

Do you have the same issue? Do you know a viable solution for this?

Thanks as usual!

**Comment by raix** [comment]
message is not invoked on background notifications that startup the app - use the startup event instead.
*(I have been thinking about merging these two into a single "message" event setting a flag "startup" or something)*

**Comment by raix** [comment]
The docs https://github.com/raix/push/blob/master/docs/ADVANCED.md#api-details is a bit misleading for the message: `// Called on every message` its not called for startup messages.

**Comment by giggioz** [comment]
Yes, it works now and yes, the doc is a little bit misleading :)
But hey, thanks again!

**Comment by teknologist** [comment]
Hi,

I tried this on iOS but the callback for startup doesn't seem to be called.

Is this normal ?

I have this on my Meteor.startup client block:

```
  Push.addListener('startup', function(notification) {
    // Called when message recieved on startup (cold+warm)
    console.log(JSON.stringify(notification));
    NotificationHistory.update({
      _id: notification.payload.historyId
    }, {
      $set: {
        "receivedAt": new Date(),
        "badge": 0
      }
    });

  });
```


Many thanks for any help you may provide. And thanks for this great package!

**Comment by teknologist** [comment]
@raix  Any idea on ^

Many thanks

**Comment by iwoj** [comment]
I'm having this problem too. "startup" isn't called when bringing an app to foreground from an app icon press instead of pressing the notification card. This is important as often users will miss the notification message, but see badges and click the app icon.

Is there any way around this?

**Comment by shivang007** [comment]
@iwoj `startup` is only called when the user opens app via notification. If you want to handle the your app startup, please use Meteor.startup.

P.S. It doesn't make sense to trigger the notification startup when user is not coming from the notification, as there is no "Context".

For this you need to maintain your in-platform notifications. 
For instance, if you open facebook from "New friend request" notification, it will take you the listing page, but if you open the app instead, you will be redirected to the Home page and you can see your notifications in notifications tab.

**Comment by shivang007** [comment]
@iwoj `startup` is only called when the user opens app via notification. If you want to handle your app startup, please use Meteor.startup.

P.S. It doesn't make sense to trigger the notification startup when user is not coming from the notification, as there is no "Context".

For this you need to maintain your in-platform notifications. 
For instance, if you open facebook from "New friend request" notification, it will take you to the listing page, but if you open the app instead, you will be redirected to the Home page and you can see your notifications in notifications tab.

**Comment by iwoj** [comment]
Thanks. Is there a collection that keeps a log of notifications, or do I have to implement my own?

**Comment by shivang007** [comment]
Yes, there will be a collection called `_raix_push_notifications` present in your DB, which stores the notification object sent by you and the status of that notification.

By default we delete the notification once it has been sent, but you can keep it stored by providing: 
```
'keepNotifications': true
```
in your server config as shown [here](https://github.com/raix/push#server)


Although, I would suggest you to maintain a separate collection for your platform alerts as you might want to show some other message on your platform, or decide to add some more details to it.
Or may not want to show all the push  notifications on platform, depending on your future requirements.

Just a suggestion.
