### ISSUE TITLE
Error while parsing query

### ISSUE THREAD

**Issue by raix** [raix/push#52]
@adeelraza: I'm having the same issue. Upgrading to 2.6.5 starts giving a different error in Modulus logs:

Exception in setInterval callback: Error: Push: Error while parsing query string

**Comment by raix** [comment]
could you try resetting the app and see if it helps?

I'll add in backwards compatibility - in the old version query was an object - now it's a string getting parsed.

**Comment by raix** [comment]
try 2.6.6

**Comment by adeelraza** [comment]
Looks good so far. Thanks! Great package!!
