### ISSUE TITLE
when app is in forground and a message is received user gets no notification

### ISSUE THREAD

**Issue by lampe** [raix/push#54]
Hey,

when i send a push notification to a android device and the app is in the forground the user gets no notification.

Tested with the lates meteor and push version on a moto g 2015 with android 5.0.2

**Comment by raix** [comment]
listen to the message event when in app

**Comment by lampe** [comment]
the events are getting fired but this is the scenario:

someone is browsing the app and gets a notifications.
This notification is a message that he has a new request
he can now accept or reject that request.

what is now happening is that without any info the app goes to the request because the event gets fired but there is no message in the android system notifications pulldown menu.

But this is what i want. the app should not switch to the dashboard without the user clicking on the notification in the pulldown menu.

i hoppe this makes my problem more clear

thx for the help !

**Comment by raix** [comment]
You should prop. user the local notifications cordova package - have the app create local notifications on messages then have an event checking if a notification have been clicked in the menu.

**Comment by lampe** [comment]
got ya!
using Toasts for inside the app!

thx!
