### ISSUE TITLE
What is the problem when the userId is not set?

### ISSUE THREAD

**Issue by miri-am** [raix/push#58]
I have the following entry in _raix_push_app_tokens. The userId is null and thus the user cannot receive any push notifications. The user was logged in several times. Do I have to call `push-setuser ` manually?
```
{ 
    "_id" : "Qf6C8ndRPaLTHkQBg", 
    "token" : {
        "gcm" : "APA91bEDL8CJNkbBsTbCzskheYftgfIjWbye6zcQd-e4Of6e1Lov_Vc7LDP9qVhI4uplRpwTO_jVtocWLD93P7iQw2dF9IRD75aFtBHTe1M20-L_1bNgOObCB9z_AEMcGAqLh3tc7VP5SVoyzZFAFAqY8uilzzQwaw"
    }, 
    "appName" : "main", 
    "userId" : null, 
    "createdAt" : ISODate("2015-04-10T15:23:38.773+0200"), 
    "updatedAt" : ISODate("2015-04-10T15:23:38.773+0200")
}
```

**Comment by miri-am** [comment]
Ok. Now I use

```
document.addEventListener('deviceready', function() {
    Push.addListener('token', function(token) {
          Session.set("token", token) ;
    });
});
```

and in the callback of the login function I use `Push.setUser`
```
 Meteor.loginWithPassword(username, password, function(error) {
    if(!error) {
         if(Session.get("token")!==undefined){
          Push.setUser(Session.get("token"));
        }
    }
}
````

**Comment by raix** [comment]
Odd,
https://github.com/raix/push/blob/master/lib/client/cordova.js#L49 should let you use Push.addListener without having to think about device ready.. Maybe we need same construct as https://github.com/raix/push/blob/master/lib/client/cordova.js#L240-L242

Should keep the userId uptodate:
https://github.com/raix/push/blob/master/lib/client/client.js#L118-L127

**Comment by miri-am** [comment]
hm. Now it seems to be working again without my code above. Possibly there was another problem.

**Comment by raix** [comment]
let me know if you see the issue again, would be nice to track down

**Comment by MoeBadr** [comment]
+1 for `userId:null`

**Comment by v3rron** [comment]
+1 for userId:null on iOS
