### ISSUE TITLE
Push Notifications Production iOS

### ISSUE THREAD

**Issue by nspangler** [raix/push#60]
Great Package! I have been throughly enjoying the capabilities that this package offers. Unfortunately I have been having problems getting push notifications to work since attempting to submit my iOS meteor-cordova app through TestFlight. I found out here http://stackoverflow.com/questions/24044298/why-push-notifications-is-not-working-on-testflight that I need production certificates in order to successfully use push notifications in test flight. Therefore I repeated the process with new production specific certificates. I checked the connection from the terminal with the new production  certificates and received:
![screen shot 2015-04-11 at 11 12 52 pm](https://cloud.githubusercontent.com/assets/5549886/7104468/50a78688-e0a0-11e4-8bfb-09838e15ce6c.png)
I then set `production:true` and did the appropriate placing and labeling of files  under `"apn"`.

     {
    "apn": {
        "passphrase": "foo",
        "key": "ProductionKey.pem",
        "cert": "Profuction.pem"
    },
    "apn-dev": {
        "passphrase": "foo",
        "key": "PushChatKey.pem",
        "cert": "PushChatCert.pem"
    },
    "production": true
  } 

On launch of the app everything seems to go fine:
![screen shot 2015-04-11 at 11 19 37 pm](https://cloud.githubusercontent.com/assets/5549886/7104484/9c34ed4c-e0a1-11e4-8deb-370b4f817022.png)

However when I attempt to send a push notification in production mode. I get  the following error:
![screen shot 2015-04-11 at 11 18 11 pm](https://cloud.githubusercontent.com/assets/5549886/7104470/18256e0a-e0a1-11e4-88af-e1ceecab257c.png)

Any idea why production mode won't be working. I have gotten push notification to work when `production:false` but I can't seem to make it work for `production:true`.

**Comment by raix** [comment]
You need to use the matching provisioning profile - your server setup looks ok

**Comment by nspangler** [comment]
So place the Distribution Provisioning Profile Certificate in the Private Folder as well?

**Comment by dennisharrison** [comment]
@nspangler No, you need a provisioning profile for iOS production, and sign your package with that profile (not the bundle name one like you can use for testing).  Hope this makes sense.

**Comment by nspangler** [comment]
@dennisharrison thanks for the response. I do have a provisioning profile for iOS production for my app but how do I sign my package with that profile?

**Comment by dennisharrison** [comment]
@nspangler I'm not in front of a machine with xCode on it so I can't give you an exact screenshot.  But it's under build settings I believe: Provisioning Profile.  That needs to be set to the one that you have iOS Production for.

**Comment by nspangler** [comment]
@dennisharrison thanks, I know how to do that. Why would that have any effect on the server crashing though?

**Comment by dennisharrison** [comment]
@nspangler This is a provisioning profile issue I'm 90% sure.

I've had the same error before.  The certificate chain isn't correct for sending push from your app to the production APN gateways.  That's the error you're seeing.

**Comment by raix** [comment]
@nspangler The problem is that the server tries to send to a test device via production certificates - so that's not normal behavior and should be prompted.

Maybe we should add a try/catch and present a nicer error message?

Eg.:
```js
  try {
    // Sending an apn message
  } catch(err) {
    if (/wrong environment/.test(err.message) {
     console.warn('You may be using the .... ');
    } else {
      throw err;
    }
  }
```

**Comment by nspangler** [comment]
@raix I think that would be helpful. 

@dennisharrison I have tried creating new provisioning profiles with distribution capabilities and still no luck. Have you been able to successfully use this package with test-flight?

**Comment by nspangler** [comment]
@raix and @dennisharrison still working on trying to figure out this problem. Is a Website Push Id needed to use to package? And if so how do I implement it into the package?
![screen shot 2015-04-14 at 9 21 38 pm](https://cloud.githubusercontent.com/assets/5549886/7151739/75c9a984-e2ec-11e4-94aa-26f849805263.png)

**Comment by nspangler** [comment]
@raix and @dennisharrison thanks for all of the help. I re-created all of my certificates and pushed an new version to my server and everything works. The provisioning profile aspect was a big help as well.
