### ISSUE TITLE
Push.appCollection.find().fetch() Still empty

### ISSUE THREAD

**Issue by zhongwus** [raix/push#62]
I tried openssl, the key works fine.

I deployed to name.meteor.com and then connect through
$ meteor run ios-device --mobile-server name.meteor.com

I added explicit bundle ID to my mobile config file.

I received token alert when I add 
Push.addListener('token', function(token) {
    alert(JSON.stringify(token));
});

However, I still get an empty appCollection. Also I tried to addListener "raix:push-update", and I received error Meteor.Error 400 Match failed.

Could anyone please help me? I tried this for a whole day but making no progress.

**Comment by zhongwus** [comment]
That is so weird. I sent many Push.send(...) yesterday, and I received one notification today!!

**Comment by raix** [comment]
try debugging your network - could there be any restrictions on ports etc.

**Comment by zhongwus** [comment]
How can I debug network? I tried Meteor.status and it says connected

**Comment by raix** [comment]
make sure the server can connect to the apn/gcm via the server ports + some networks cut off ports used by push - depending on security levels

**Comment by zhongwus** [comment]
I'm using name.meteor.com server, how to check if the server can connect to apn/gcm via the server ports? Sorry I'm new to server ports

**Comment by zhongwus** [comment]
Thank you! I think it's working now. After I deployed to meteor server, I can receive notifications as I expected. But it is strange that when I run meteor shell, appCollection is still empty, no matter I use --mobile-server or not.
