### ISSUE TITLE
No sound or vibration in ios 

### ISSUE THREAD

**Issue by MoeBadr** [raix/push#63]
Hi, 
I'm currently testing push on ios & android side by side, I'm unable to get sound & vibration to work in ios but it works fine for android, sample code of `push.send()`: 

```javascript
Push.send({
    from: 'xx',
    title: 'New Message',
    text: message,
    badge: 1,
    sound: 'default',
    query: { userId: userId }
});
```
I also have, `sound`, `vibrate` set to `true` in my `config.push.json`.

Thank you for any help in advance.

**Comment by kylepierce** [comment]
Any suggestions on how your fixed it?

**Comment by mitiaptest** [comment]
@MoeBadr can you please help me on this issue?

**Comment by MoeBadr** [comment]
This is my setup which works fine for both iOS & Android: 

**config.push.json**

```javascript
{
  "apn": {
    "passphrase": "x",
    "key": "x.pem",
    "cert": "x.pem"
  },
  "apn-dev": {
    "passphrase": "x",
    "key": "x.pem",
    "cert": "x.pem"
  },
  "gcm": {
    "apiKey": "x",
    "projectNumber": "x"
  },
  "production": true,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true
}
````

**Sending**
```javascript

    Push.send({
            from: 'x',
            title: title,
            text: message,
            badge: 1,
            sound: 'default',
            query: {
                userId: { $in: userIds }
            }
        })
````

**Comment by mitiaptest** [comment]
@MoeBadr  I also having same configuration settings.Apart from this have you installed any extra plug-in to work vibration?

**Comment by MoeBadr** [comment]
@mitiaptest No, I'm not making use of any other packages. p.s make sure your phone's settings are not the issue.

**Comment by mitiaptest** [comment]
Have you tested this on iOS? Phone setting are correct no issue with that. Vibration is already enabled in Phone settings.

**Comment by MoeBadr** [comment]
Yes, above config is currently used for production. No issues reported so far.

**Comment by mitiaptest** [comment]
which raix:push version you are using?

**Comment by mitiaptest** [comment]
@ MoeBadr  Need your help.

**Comment by MoeBadr** [comment]
@mitiaptest currently on @3.0.2

**Comment by MoeBadr** [comment]
@mitiaptest if I can remember correctly, we had a couple of issues with server network configuration which also caused issues with push.

**Comment by mitiaptest** [comment]
@MoeBadr Notifications arrives without sound and vibration.

**Comment by MoeBadr** [comment]
@mitiaptest in that cause, please ignore my comment about  "server network configuration". I'm currently doing more testing. I will keep you updated.

**Comment by mitiaptest** [comment]
@MoeBadr Thanks.
