### ISSUE TITLE
Multiple Servos Send Duplicate Notifications

### ISSUE THREAD

**Issue by davidwoody** [raix/push#65]
If you are running multiple servos the send fence is only protecting the one environment. The fix would be to have a "send fence" be database driven.

Existing Fence:
https://github.com/raix/push/blob/60bc871be12a33295e3202563c88863f79f0def4/lib/server/push.api.js#L422

Suggested update, something like this:
https://github.com/raix/push/blob/60bc871be12a33295e3202563c88863f79f0def4/lib/server/push.api.js#L427

```
var notification = Push.notifications.findOne({ sending: {$ne: true}, sent : { $ne: true } }, { sort: { createdAt: 1 } });

if(notification) {
  var selector = {
     _id: notification._id,
     sending: false,
     sent: false
  };
  var modifier = {
     $set: {
        sending: true
     }
  };
  var numberOfDocsUpdated = Push.notifications.update(selector, modifier);

  if(numberOfDocsUpdated === 1) {
      //proceed with sending
  }
}
```

If the server crashed in-between updating to `sending: true` and finishing the send, that particular push notification would be stuck in limbo, so the only other thing to add is a process thats moves the "sending" back to false if a push notification `sending: true` has not been completed within a certain time period.

**Comment by raix** [comment]
Thanks, I thought this was already pushed - I'm sure I've already done this... I'll check up on it

**Comment by raix** [comment]
@davidwoody can you give `raix:push@2.6.7-pre.1` a go?

**Comment by davidwoody** [comment]
@raix BOOM! Looks fixed to me. Just tried it out in staging and production and it worked like a charm. Thanks!
