### ISSUE TITLE
iOS notification is unreliable 

### ISSUE THREAD

**Issue by MoeBadr** [raix/push#76]
Hi All, 

We've been using this great package for few weeks now, Thank you all for the contribution. 

We are running into some problems with iOS notification as it's unreliable (sometimes it works, other times it does not). For example, 
1. user downloads app 
2. user registers 

In the above scenario notifications are not received. but if 

1. user downloads app 
2. user registers
3. user logs out and logs back in 

in the above scenario notifications work fine sometimes and sometimes they do not. 

please advice on potential issues that might cause the notification not to work. 

Any help is very much appreciated. 

Thank you.

**Comment by Tim-W** [comment]
I'm using this package for APN notifications and noticed this as well. I will be investigating this and will try to describe the relation between success/failure and the environment.

**Comment by Tim-W** [comment]
It seems that APN notifications work well when the app is deployed to xxx.meteor.com but not when testing locally on server 192.168.x.x:3000

**Comment by raix** [comment]
@Tim-W might be your network? try disabling you phones wifi

**Comment by MoeBadr** [comment]
@Tim-W ,  I currently running meteor on aws beanstalk in production mode with production cert & key.

**Comment by MoeBadr** [comment]
@raix the difference I've noticed when running the app on an iOS and Android device is if I check  the app is connected to the server using the following `Meteor.status().connected`, it often returns `false` when opening the app (iOS), compare to the Android device which happens a lot less often. Can this be the issue as it seems to disconnect from the server when running in the background ?

**Comment by Tim-W** [comment]
Never mind. It works now, I hadn't included my iPhone in the provisioning file. It works fine now.

**Comment by fpoirier1** [comment]
I've noticed that when the user gets into the app for the first time the debug message looks like this : 
````
Push: Got push token from app: { id: 'uCRuEE4Y4hZMmgziJ',
  token: { apn: '0793cv19c8a93c8cf8962d1316c6b74f36d72e18e44ceeaf298b4e087d066c73' },
  appName: 'main',
  userId: null,
  metadata: {} }
```
Looks like we have to wait for the user to come back in the app to assign a `userId` to the `token` because of the auto-login.
