### ISSUE TITLE
Reporting location on demand

### ISSUE THREAD

**Issue by uriva** [raix/push#77]
Hi fellas

I have a branch of pushplugin with some added functionality (as of now just on android).
It enables defining a server http endpoint via javascript and sending back location upon a GCM with REPORT_LOCATION in a certain field without bothering the user.
(It can't be done from javascript because the app is not always active)
This is useful when the server needs accurate client location in a specific time, but periodically updating the server costs precious battery.

I thought about branching this and integrating it with my pushplugin, but as it is a common use case, perhaps you'd want to incorporate it here?
This way the endpoint could also be prepared without developer having to define it.

**Comment by raix** [comment]
interesting idea - so you would use background push notifications to get the user location? - on ios this can only be done once a day?

**Comment by uriva** [comment]
I'm not really familiar with iOS
I just assumed you can run code upon APN and then just send the info back in http request like I do in android.

**Comment by uriva** [comment]
Just saw there is a seemingly better cordova push plugin (PushPlugin appears abandoned)
https://github.com/phonegap/phonegap-plugin-push

**Comment by raix** [comment]
I use this: https://github.com/raix/PushPlugin - trying to keep it updated

**Comment by uriva** [comment]
ok.
care to pull there?

**Comment by raix** [comment]
sure

**Comment by uriva** [comment]
Closing this, as it would appear the right place to implement this is phonegap:phonegap-plugin-push

**Comment by raix** [comment]
Yeah - they have deprecated the old PushPlugin in favor of https://github.com/phonegap/phonegap-plugin-push
