### ISSUE TITLE
Duplicate entries in appCollection

### ISSUE THREAD

**Issue by netanelgilad** [raix/push#78]
Hey @raix, thanks for the cool package.
I'm experiencing an issue with listening on the `message` event on mobile. For some reason it gets called more than once (sometimes even three and four times), causing my app to display popup multiple times on notifications.
What I noticed is that the appCollection has more than one entry for the same user and token. This is from the meteor shell command:

```
Push.appCollection.find({}).fetch()
[ { _id: 'r8As3j8urjFjGGSzh',
    token: { gcm: 'APA91bEPWxaTsEwHEhHYMmwN_7xB4mIvq8sp4P_LSa-HIJpVUu4idf7buP8O95PoMVMStPN3LkUCBfyiv24PbiZI821YCCrInBLQ78TrKCfJeLRwP_NPVG2kUcSE0QjcLSIC7v5B55e1' },
    appName: 'main',
    userId: 'wSxpQZ5t677xZyHvA',
    createdAt: Sun May 31 2015 17:01:58 GMT+0300 (IDT),
    updatedAt: Sun May 31 2015 17:01:58 GMT+0300 (IDT) },
  { _id: 'vjMszDvrj53x5jLrB',
    token: { gcm: 'APA91bEPWxaTsEwHEhHYMmwN_7xB4mIvq8sp4P_LSa-HIJpVUu4idf7buP8O95PoMVMStPN3LkUCBfyiv24PbiZI821YCCrInBLQ78TrKCfJeLRwP_NPVG2kUcSE0QjcLSIC7v5B55e1' },
    appName: 'main',
    userId: 'wSxpQZ5t677xZyHvA',
    createdAt: Sun May 31 2015 18:43:23 GMT+0300 (IDT),
    updatedAt: Sun May 31 2015 19:15:45 GMT+0300 (IDT) } ]
```

Seems like a bug, or maybe I'm missing something..

**Comment by raix** [comment]
looks like a bug - the code should try to find existing tokens for the user/id and merge those.

**Comment by conorstrejcek** [comment]
+1 This is happening for me as well.

**Comment by Alveoli** [comment]
+1 happened for me though I couldn't reproduce it reliably yet. Seems to be something to do with installing and installing the app on the same device many times - the appCollection then contains multiple entries with the same token.

BTW @raix thanks for the amazing package!

**Comment by Alveoli** [comment]
Some additional info - I installed/uninstalled 3 times on one device. For each installation there was one line in appCollection. The 3rd time, I built a new version; when it booted up, it overwrote all the token.gcm to be the same token... after that, it got notifications in triplicate.

Good news is that if it's a background notification, the device only seems to get one alert... so this bug's effect is limited to situations where the app is in the foreground.

(In case it matters - I'm using Android only.)

**Comment by raix** [comment]
thanks guys - I'll see if I can find some time soon to fix this - please feel free to investigate further. I also take pr's :)

ref:
https://github.com/raix/push/blob/master/lib/client/client.js#L91
https://github.com/raix/push/blob/master/lib/server/server.js#L39
