### ISSUE TITLE
Question (not bug) Any thoughts on badgecount / performance impact?

### ISSUE THREAD

**Issue by adamgins** [raix/push#8]
Hi,

this is more a best practices type of question - not sure if I should be posting here, but it's directly related to this package.

wondering what the best way would be to handle badges, in a situation where there could be a high volume of notifications?

One option is when you send a push notification you can just could just see how many unread notifications a user has (assuming folk would be tracking this in a separate "notifications" collection) and then set the badge count to that number. Although, this would be referentially correct, it seems like an expensive thing to do each time someone does something like comment/send a message - assuming you wanted to have push notifications for the capability. 

Are there any better ways that would require less processing per push notification and se the badge count?

BTW, I do see `Push.setBadge(count);` for iOS... but doing this client side would not update the App icon/badge... ie guess another option is doing this once ever X seconds (so the bade would be out of sync between updates?

**Comment by adamgins** [comment]
Thanks. Yep I had thought of `Push.setBadge(count);` on the client... but this only keeps it accurate when the app is open, right?

So, in the case of the app is closed (eg looking at home screen) the badge count won't change unless the sender sets it. Do I have that right?

I could try and cache it on the user doc, so the sender has to do less processing, but this would be fraught with multiple users all trying to update the same user docs. (eg if you wanted push notifications on a multi-way chat).

I think this is a pretty common use case, so just wondering if other have solved this with any smarter approaches?

**Comment by adamgins** [comment]
@raix is there a reason my badges disappear when I hit the home button (close the app and go to home screen)? This only seems to happen if open the app then then close it without setting the badge count manually.

Scenario 1 -  Let's say badge count is 5, I open the app. Then close it (I don't call anything to do with badges) it wipes out all the badges.  (I don't think I am reseting the badge count anywhere - not sure if some event is?)

Scenario 2 -  Badge count is 5,  I open it and mark one item as read and reset the badge count to 4 and then close it, it shows the badge count as 4.

thanks

**Comment by raix** [comment]
related to issue #25 - I think it would be nice to have a counter for non-specific messages (this would reset on open) and have count object with keys set as id. So the total counter would be a mix of those two.

+ there should be a limit of how many messages the server allows the user to have hanging before stopping sending messages / considering the user inactive.

(this is the current logic I have in one of my apps - it's very useful)

**Comment by raix** [comment]
Tracking this in #45
