### ISSUE TITLE
How to view contents of _raix_push_notifications and _raix_push_app_tokens

### ISSUE THREAD

**Issue by torayeff** [raix/push#81]
After deploying meteor application with mup deploy I wanted to see the entries in _raix_push_app_tokens. But I receive this error:
```
> db._raix_push_app_tokens.find().fetch()
2015-06-09T06:47:23.951-0400 TypeError: Cannot call method 'find' of undefined
```
Push notifications work, I just want to inspect entries.

**Comment by raix** [comment]
use `meteor shell`

**Comment by torayeff** [comment]
@raix I can not use ```meteor shell``` on production app. I need to clean ```_raix_push_notifications and _raix_push_app_tokens``` after redeploying, because it registers for same android device several times and I do not receive any notifications.
P.S.: Why it is not possible to view ```_raix_push_notifications and _raix_push_app_tokens``` just by usual way?

**Comment by ppryde** [comment]
Just incase anyone else comes across this issue you can use getCollection in MongoDb to view collection names starting with an underscore:

`db.getCollection('_raix_push_app_tokens').find()`
`db.getCollection('_raix_push_notifications').find()`

**Comment by torayeff** [comment]
thanks @ppryde

**Comment by Tzikas** [comment]
thanks @ppryde

**Comment by KristerV** [comment]
wow thanks a lot @ppryde
