### ISSUE TITLE
message vibration and sound on iOS 8?

### ISSUE THREAD

**Issue by SonofBSOD** [raix/push#82]
Hi there! Thanks so much for this push package, it has really made setting up notifications a lot easier on Android and iOS. I was just wondering if anyone ran into a problem with vibrations or sound on iOS.

The messages work on my iOS app, but they do not trigger any sound or vibration when received, regardless whether the app is in the foreground or background. I've set production:"false", alert:"true", sound:"true" and vibrate:"true" in push.config.json. I looked/traced around the package code, and found out that 'navigator.notification.vibrate' is undefined when the default event handlers run (e.g. "message" and "sound" in client/cordova.js). I then tried to install the cordova-plugin-vibration directly with 'cordova plugin add cordova-plugin-vibration'.

With that, I got a vibration, but no sound, when I received a notification while the app was running in the foreground with a custom "alert" event listener that just displayed a popup with the message. Unfortunately, background notifications had neither sound nor vibration. 

I've checked my phone settings and made sure that the dependencies for the raix:push package were installed as well, e.g. raix:cordova, raix:eventstate. When XCode pops up after I run 'meteor run --ios-device --mobile-server fakeservername.com', I can see CDVVibration and CDVNotification .m and .h files under the plugins directory. Could it be they are not being loaded correctly?

Would anyone happen to know if I did something incorrectly, or how I could fix this issue?

**Comment by shanshuo0918** [comment]
Hi @SonofBSOD I have exactly the same issue as you. Could you let me know how did you solve the problem?

**Comment by Tim-W** [comment]
ditto

**Comment by rlech** [comment]
+1

**Comment by haunguyen90** [comment]
I have same issue, @raix is there any way for fix it ?

**Comment by Streemo** [comment]
i'm also having this issue

**Comment by Streemo** [comment]
anyone find a fix?

**Comment by mitiaptest** [comment]
+1

**Comment by mitiaptest** [comment]
@SonofBSOD can you please help me on this?

**Comment by nddeveloper** [comment]
No Sound No Vibration 

Is there any way to solve this issue @raix

**Comment by jpgilchrist** [comment]
Why was this closed. @raix  @SonofBSOD seems like several people are having this issue, including myself.

**Comment by jpgilchrist** [comment]
Ah. After reading through some other tickets I see the solution, and understand why it's closed. Just because the app is configured to play sounds and vibrate, you actually have to send a sound with the notification... if you don't send a sound with the notification there's nothing to play.
