### ISSUE TITLE
Emit events when receive method calls to change token

### ISSUE THREAD

**Issue by rodrigok** [raix/push#98]
What do you think about emit some events inside methods?

We need more controle over tokens to improve performance of our application, with this events I can save tokens inside user's record to improve some finds.

**Comment by raix** [comment]
Events could easily be added - the documentation might lack on some of the existing events - theres a server-side `Push.on('token', function(token){})` that is triggered inside the server method.

It would be helpful to me if you would list ideas for events and where/what they should emit

**Comment by rodrigok** [comment]
I tried to use the token event with no success.

So, I can create a PR with my ideas, what do you think?

**Comment by raix** [comment]
sure, we can do that and have it up for discussion

**Comment by rodrigok** [comment]
Hey @raix, we realized that this will not solve our problem. I will close this issue and open another with a new idea/necessity.
